// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { createHashHistory, createMemoryHistory, createBrowserHistory, History } from '@fs/Users/congxiaochen/Documents/alita/node_modules/.pnpm/@umijs+renderer-react@4.0.0-rc.1_react-dom@17.0.2+react@17.0.2/node_modules/@umijs/renderer-react';

let history: History;
export function createHistory(opts: any) {
  if (opts.type === 'hash') {
    history = createHashHistory();
  } else if (opts.type === 'memory') {
    history = createMemoryHistory();
  } else {
    history = createBrowserHistory();
  }
  return history;
}

export { history };
