// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export async function getRoutes() {
  return {
    routes: {"users/index":{"path":"users","id":"users/index","parentId":"alita-layout","file":"users/index.tsx"},"foo/index":{"path":"foo","id":"foo/index","parentId":"alita-layout","file":"foo/index.tsx"},"index":{"path":"/","id":"index","parentId":"alita-layout","file":"index.tsx"},"alita-layout":{"id":"alita-layout","path":"/","file":"/Users/congxiaochen/Documents/alita/examples/boilerplate/src/.umi-production/plugin-mobile-layout/AlitaLayout.tsx"}},
    routeComponents: {
'users/index': () => import('../../../src/pages/users/index.tsx'),
'foo/index': () => import('../../../src/pages/foo/index.tsx'),
'index': () => import('../../../src/pages/index.tsx'),
'alita-layout': () => import('../plugin-mobile-layout/AlitaLayout.tsx'),
},
  };
}
