// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { request } from '@fs/Users/congxiaochen/Desktop/poplar/node_modules/@alita/request';
export { useRequest } from '@fs/Users/congxiaochen/Desktop/poplar/node_modules/ahooks';
