// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { _InspxContainer } from './inspx';

export function rootContainer(container) {
  return React.createElement(_InspxContainer, null, container);
}
