"use strict";(self.webpackChunkalita3=self.webpackChunkalita3||[]).push([[292],{38666:function(j,r,l){l.r(r);var i=l(57213),c=l.n(i),d=l(93236),s=l(62086);function h(){var n=arguments.length>0&&arguments[0]!==void 0?arguments[0]:{};(0,d.useEffect)(function(){var e;if(window.location.hash.length!==0){var p=decodeURIComponent(window.location.hash);setTimeout(function(){var a;(a=document.getElementById(p.slice(1)))===null||a===void 0||a.scrollIntoView()},100)}else window.scrollTo(0,0);(e=document.getElementById("active-nav-item"))===null||e===void 0||e.scrollIntoView({behavior:"smooth",block:"center"})},[]);var D=n.components||{},o=D.wrapper;return o?(0,s.jsx)(o,c()(c()({},n),{},{children:(0,s.jsx)(t,{})})):t();function t(){var e=Object.assign({h1:"h1",a:"a",span:"span",h2:"h2",div:"div",pre:"pre",code:"code"},n.components);return(0,s.jsxs)(s.Fragment,{children:[(0,s.jsxs)(e.h1,{id:"\u624B\u52BF\u5BC6\u7801",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u624B\u52BF\u5BC6\u7801",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u624B\u52BF\u5BC6\u7801"]}),`
`,(0,s.jsx)("img",{height:"300",src:"https://user-images.githubusercontent.com/11746742/68995608-735b4a00-08ca-11ea-8402-2d5229beaceb.png"}),`
`,(0,s.jsxs)(e.h2,{id:"install",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#install",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"install"]}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"bash","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"bash","data-theme":"default",children:[(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"// npm"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"npm install @alitajs/gesture-password-react --save"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"// yarn"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"yarn add @alitajs/gesture-password-react"})})]})})}),`
`,(0,s.jsxs)(e.h2,{id:"usage",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#usage",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"usage"]}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"React"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'react'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"GesturePassword"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'@alitajs/gesture-password-react'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" () "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#4FC1FF"},children:"config"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"width:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#B5CEA8"},children:"375"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"height:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#B5CEA8"},children:"300"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"onChange"}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"data"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"any"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"console"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"log"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"data"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"), "}),(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// get gesture password"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  };"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" <"}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"GesturePassword"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {..."}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"config"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"} />;"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"};"})})]})})})]})}}r.default=h}}]);
