"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[137],{38229:function(p,a,n){n.r(a);var t=n(55980),c=n.n(t),d=n(93236),e=n(62086);function h(){var l=arguments.length>0&&arguments[0]!==void 0?arguments[0]:{};(0,d.useEffect)(function(){var s;if(window.location.hash.length!==0){var x=decodeURIComponent(window.location.hash);setTimeout(function(){var r;(r=document.getElementById(x.slice(1)))===null||r===void 0||r.scrollIntoView()},100)}else window.scrollTo(0,0);(s=document.getElementById("active-nav-item"))===null||s===void 0||s.scrollIntoView({behavior:"smooth",block:"center"})},[]);var D=l.components||{},o=D.wrapper;return o?(0,e.jsx)(o,c()(c()({},l),{},{children:(0,e.jsx)(i,{})})):i();function i(){var s=Object.assign({h1:"h1",a:"a",span:"span",p:"p",h2:"h2",code:"code",h3:"h3",div:"div",pre:"pre",ul:"ul",li:"li"},l.components);return(0,e.jsxs)(e.Fragment,{children:[(0,e.jsxs)(s.h1,{id:"\u8FD0\u884C\u65F6\u914D\u7F6E",children:[(0,e.jsx)(s.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u8FD0\u884C\u65F6\u914D\u7F6E",children:(0,e.jsx)(s.span,{className:"icon icon-link"})}),"\u8FD0\u884C\u65F6\u914D\u7F6E"]}),`
`,(0,e.jsx)(s.p,{children:"\u8FD0\u884C\u65F6\u914D\u7F6E\u548C\u914D\u7F6E\u7684\u533A\u522B\u662F\u4ED6\u8DD1\u5728\u6D4F\u89C8\u5668\u7AEF\uFF0C\u57FA\u4E8E\u6B64\uFF0C\u6211\u4EEC\u53EF\u4EE5\u5728\u8FD9\u91CC\u5199\u51FD\u6570\u3001tsx\u3001import \u6D4F\u89C8\u5668\u7AEF\u4F9D\u8D56\u7B49\u7B49\uFF0C\u6CE8\u610F\u4E0D\u8981\u5F15\u5165 node \u4F9D\u8D56\u3002"}),`
`,(0,e.jsxs)(s.h2,{id:"\u914D\u7F6E\u65B9\u5F0F",children:[(0,e.jsx)(s.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u914D\u7F6E\u65B9\u5F0F",children:(0,e.jsx)(s.span,{className:"icon icon-link"})}),"\u914D\u7F6E\u65B9\u5F0F"]}),`
`,(0,e.jsxs)(s.p,{children:["\u7EA6\u5B9A ",(0,e.jsx)(s.code,{children:"src/app.tsx"})," \u4E3A\u8FD0\u884C\u65F6\u914D\u7F6E\u3002"]}),`
`,(0,e.jsxs)(s.h2,{id:"\u914D\u7F6E\u9879",children:[(0,e.jsx)(s.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u914D\u7F6E\u9879",children:(0,e.jsx)(s.span,{className:"icon icon-link"})}),"\u914D\u7F6E\u9879"]}),`
`,(0,e.jsxs)(s.h3,{id:"onroutechange-routes-clientroutes-location-action-",children:[(0,e.jsx)(s.a,{"aria-hidden":"true",tabIndex:"-1",href:"#onroutechange-routes-clientroutes-location-action-",children:(0,e.jsx)(s.span,{className:"icon icon-link"})}),"onRouteChange({ routes, clientRoutes, location, action })"]}),`
`,(0,e.jsx)(s.p,{children:"\u5728\u521D\u59CB\u52A0\u8F7D\u548C\u8DEF\u7531\u5207\u6362\u65F6\u505A\u4E00\u4E9B\u4E8B\u60C5\u3002"}),`
`,(0,e.jsx)(s.p,{children:"\u6BD4\u5982\u7528\u4E8E\u505A\u57CB\u70B9\u7EDF\u8BA1\uFF0C"}),`
`,(0,e.jsx)(s.div,{"data-rehype-pretty-code-fragment":"",children:(0,e.jsx)(s.pre,{"data-language":"bash","data-theme":"default",children:(0,e.jsxs)(s.code,{"data-language":"bash","data-theme":"default",children:[(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#569CD6"},children:"export"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#569CD6"},children:"function"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#DCDCAA"},children:"onRouteChange({"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" location, routes, action }) {"})]}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"  bacon(location.pathname);"})}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,e.jsx)(s.p,{children:"\u6BD4\u5982\u7528\u4E8E\u8BBE\u7F6E\u6807\u9898\uFF0C"}),`
`,(0,e.jsx)(s.div,{"data-rehype-pretty-code-fragment":"",children:(0,e.jsx)(s.pre,{"data-language":"bash","data-theme":"default",children:(0,e.jsxs)(s.code,{"data-language":"bash","data-theme":"default",children:[(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#569CD6"},children:"export"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#569CD6"},children:"function"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#DCDCAA"},children:"onRouteChange({"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" clientRoutes }) {"})]}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"  "}),(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"if"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" (clientRoutes.length) {"})]}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"    document.title = clientRoutes[clientRoutes.length - 1].route.title || "}),(0,e.jsx)(s.span,{style:{color:"#CE9178"},children:"''"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"  }"})}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,e.jsxs)(s.h3,{id:"patchroutes-routes-",children:[(0,e.jsx)(s.a,{"aria-hidden":"true",tabIndex:"-1",href:"#patchroutes-routes-",children:(0,e.jsx)(s.span,{className:"icon icon-link"})}),"patchRoutes({ routes })"]}),`
`,(0,e.jsxs)(s.h3,{id:"patchclientroutes-routes-",children:[(0,e.jsx)(s.a,{"aria-hidden":"true",tabIndex:"-1",href:"#patchclientroutes-routes-",children:(0,e.jsx)(s.span,{className:"icon icon-link"})}),"patchClientRoutes({ routes })"]}),`
`,(0,e.jsx)(s.p,{children:"\u4FEE\u6539\u8DEF\u7531\u3002"}),`
`,(0,e.jsxs)(s.p,{children:["\u6BD4\u5982\u5728\u6700\u524D\u9762\u6DFB\u52A0\u4E00\u4E2A ",(0,e.jsx)(s.code,{children:"/foo"})," \u8DEF\u7531\uFF0C"]}),`
`,(0,e.jsx)(s.div,{"data-rehype-pretty-code-fragment":"",children:(0,e.jsx)(s.pre,{"data-language":"bash","data-theme":"default",children:(0,e.jsxs)(s.code,{"data-language":"bash","data-theme":"default",children:[(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#569CD6"},children:"export"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#569CD6"},children:"function"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#DCDCAA"},children:"patchRoutes({"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" routes }) {"})]}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"  routes.unshift({"})}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"    path: "}),(0,e.jsx)(s.span,{style:{color:"#CE9178"},children:"'/foo'"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"    exact: true,"})}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"    component: require("}),(0,e.jsx)(s.span,{style:{color:"#CE9178"},children:"'@/extraRoutes/foo'"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:").default,"})]}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"  });"})}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,e.jsxs)(s.p,{children:["\u6BD4\u5982\u548C ",(0,e.jsx)(s.code,{children:"render"})," \u914D\u7F6E\u914D\u5408\u4F7F\u7528\uFF0C\u8BF7\u6C42\u670D\u52A1\u7AEF\u6839\u636E\u54CD\u5E94\u52A8\u6001\u66F4\u65B0\u8DEF\u7531\uFF0C"]}),`
`,(0,e.jsx)(s.div,{"data-rehype-pretty-code-fragment":"",children:(0,e.jsx)(s.pre,{"data-language":"bash","data-theme":"default",children:(0,e.jsxs)(s.code,{"data-language":"bash","data-theme":"default",children:[(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#DCDCAA"},children:"let"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" extraRoutes;"})]}),`
`,(0,e.jsx)(s.span,{className:"line",children:" "}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#569CD6"},children:"export"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#569CD6"},children:"function"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#DCDCAA"},children:"patchRoutes({"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" routes }) {"})]}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"  merge(routes, extraRoutes);"})}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"}"})}),`
`,(0,e.jsx)(s.span,{className:"line",children:" "}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#569CD6"},children:"export"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#569CD6"},children:"function"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#DCDCAA"},children:"render(oldRender)"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"  fetch("}),(0,e.jsx)(s.span,{style:{color:"#CE9178"},children:"'/api/routes'"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:").then(res=>res.json()).then"}),(0,e.jsx)(s.span,{style:{color:"#CE9178"},children:"((res) "}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"=>"}),(0,e.jsx)(s.span,{style:{color:"#CE9178"},children:" {"})]}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"    extraRoutes = res.routes;"})}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"    "}),(0,e.jsx)(s.span,{style:{color:"#DCDCAA"},children:"oldRender"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"  })"})}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,e.jsx)(s.p,{children:"\u6CE8\u610F\uFF1A"}),`
`,(0,e.jsxs)(s.ul,{children:[`
`,(0,e.jsx)(s.li,{children:"\u76F4\u63A5\u4FEE\u6539 routes\uFF0C\u4E0D\u9700\u8981\u8FD4\u56DE"}),`
`]}),`
`,(0,e.jsxs)(s.h3,{id:"renderoldrender-function",children:[(0,e.jsx)(s.a,{"aria-hidden":"true",tabIndex:"-1",href:"#renderoldrender-function",children:(0,e.jsx)(s.span,{className:"icon icon-link"})}),"render(oldRender: ",(0,e.jsx)(s.code,{children:"Function"}),")"]}),`
`,(0,e.jsx)(s.p,{children:"\u8986\u5199 render\u3002"}),`
`,(0,e.jsx)(s.p,{children:"\u6BD4\u5982\u7528\u4E8E\u6E32\u67D3\u4E4B\u524D\u505A\u6743\u9650\u6821\u9A8C\uFF0C"}),`
`,(0,e.jsx)(s.div,{"data-rehype-pretty-code-fragment":"",children:(0,e.jsx)(s.pre,{"data-language":"bash","data-theme":"default",children:(0,e.jsxs)(s.code,{"data-language":"bash","data-theme":"default",children:[(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"import { "}),(0,e.jsx)(s.span,{style:{color:"#DCDCAA"},children:"history"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" } from "}),(0,e.jsx)(s.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,e.jsx)(s.span,{className:"line",children:" "}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#569CD6"},children:"export"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#569CD6"},children:"function"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#DCDCAA"},children:"render(oldRender)"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"  fetch("}),(0,e.jsx)(s.span,{style:{color:"#CE9178"},children:"'/api/auth'"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:").then(auth => {"})]}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"    "}),(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"if"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" (auth.isLogin) { "}),(0,e.jsx)(s.span,{style:{color:"#DCDCAA"},children:"oldRender"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"() }"})]}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"    "}),(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"else"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"      history.push("}),(0,e.jsx)(s.span,{style:{color:"#CE9178"},children:"'/login'"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"      "}),(0,e.jsx)(s.span,{style:{color:"#DCDCAA"},children:"oldRender"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"()"})]}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"    }"})}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"  });"})}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,e.jsxs)(s.h3,{id:"request",children:[(0,e.jsx)(s.a,{"aria-hidden":"true",tabIndex:"-1",href:"#request",children:(0,e.jsx)(s.span,{className:"icon icon-link"})}),"request"]}),`
`,(0,e.jsxs)(s.p,{children:["\u5982\u679C\u4F60\u4F7F\u7528\u4E86 ",(0,e.jsx)(s.code,{children:"import { request } from 'umi';"})," \u6765\u8BF7\u6C42\u6570\u636E\uFF0C\u90A3\u4E48\u4F60\u53EF\u4EE5\u901A\u8FC7\u8BE5\u914D\u7F6E\u6765\u81EA\u5B9A\u4E49\u4E2D\u95F4\u4EF6\u3001\u62E6\u622A\u5668\u3001\u9519\u8BEF\u5904\u7406\u9002\u914D\u7B49\u3002"]}),`
`,(0,e.jsx)(s.p,{children:"TODO: \u8865\u5145 request \u914D\u7F6E\u6587\u6863"}),`
`,(0,e.jsxs)(s.h3,{id:"rootcontainerlastrootcontainer-args",children:[(0,e.jsx)(s.a,{"aria-hidden":"true",tabIndex:"-1",href:"#rootcontainerlastrootcontainer-args",children:(0,e.jsx)(s.span,{className:"icon icon-link"})}),"rootContainer(lastRootContainer, args)"]}),`
`,(0,e.jsx)(s.p,{children:"\u4FEE\u6539\u4EA4\u7ED9 react-dom \u6E32\u67D3\u65F6\u7684\u6839\u7EC4\u4EF6\u3002"}),`
`,(0,e.jsx)(s.p,{children:"\u6BD4\u5982\u7528\u4E8E\u5728\u5916\u9762\u5305\u4E00\u4E2A Provider\uFF0C"}),`
`,(0,e.jsx)(s.div,{"data-rehype-pretty-code-fragment":"",children:(0,e.jsx)(s.pre,{"data-language":"js","data-theme":"default",children:(0,e.jsxs)(s.code,{"data-language":"js","data-theme":"default",children:[(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"export"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#569CD6"},children:"function"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#DCDCAA"},children:"rootContainer"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"("}),(0,e.jsx)(s.span,{style:{color:"#9CDCFE"},children:"container"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"  "}),(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"return"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#9CDCFE"},children:"React"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"."}),(0,e.jsx)(s.span,{style:{color:"#DCDCAA"},children:"createElement"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"("}),(0,e.jsx)(s.span,{style:{color:"#9CDCFE"},children:"ThemeProvider"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:", "}),(0,e.jsx)(s.span,{style:{color:"#569CD6"},children:"null"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:", "}),(0,e.jsx)(s.span,{style:{color:"#9CDCFE"},children:"container"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,e.jsx)(s.p,{children:"args \u5305\u542B\uFF1A"}),`
`,(0,e.jsxs)(s.ul,{children:[`
`,(0,e.jsx)(s.li,{children:"routes\uFF0C\u5168\u91CF\u8DEF\u7531\u914D\u7F6E"}),`
`,(0,e.jsx)(s.li,{children:"plugin\uFF0C\u8FD0\u884C\u65F6\u63D2\u4EF6\u673A\u5236"}),`
`,(0,e.jsx)(s.li,{children:"history\uFF0Chistory \u5B9E\u4F8B"}),`
`]}),`
`,(0,e.jsxs)(s.h2,{id:"\u66F4\u591A\u914D\u7F6E",children:[(0,e.jsx)(s.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u66F4\u591A\u914D\u7F6E",children:(0,e.jsx)(s.span,{className:"icon icon-link"})}),"\u66F4\u591A\u914D\u7F6E"]}),`
`,(0,e.jsx)(s.p,{children:"Alita \u5141\u8BB8\u63D2\u4EF6\u6CE8\u518C\u8FD0\u884C\u65F6\u914D\u7F6E\uFF0C\u5982\u679C\u4F60\u4F7F\u7528\u63D2\u4EF6\uFF0C\u80AF\u5B9A\u4F1A\u5728\u63D2\u4EF6\u91CC\u627E\u5230\u66F4\u591A\u8FD0\u884C\u65F6\u7684\u914D\u7F6E\u9879\u3002"})]})}}a.default=h}}]);
