"use strict";(self.webpackChunkalita3=self.webpackChunkalita3||[]).push([[854],{34073:function(j,c,e){e.r(c);var o=e(57213),i=e.n(o),t=e(93236),s=e(62086);function h(){var n=arguments.length>0&&arguments[0]!==void 0?arguments[0]:{};(0,t.useEffect)(function(){var l;if(window.location.hash.length!==0){var D=decodeURIComponent(window.location.hash);setTimeout(function(){var r;(r=document.getElementById(D.slice(1)))===null||r===void 0||r.scrollIntoView()},100)}else window.scrollTo(0,0);(l=document.getElementById("active-nav-item"))===null||l===void 0||l.scrollIntoView({behavior:"smooth",block:"center"})},[]);var x=n.components||{},a=x.wrapper;return a?(0,s.jsx)(a,i()(i()({},n),{},{children:(0,s.jsx)(d,{})})):d();function d(){var l=Object.assign({h1:"h1",a:"a",span:"span",p:"p",code:"code",h2:"h2",div:"div",pre:"pre",table:"table",thead:"thead",tr:"tr",th:"th",tbody:"tbody",td:"td",h3:"h3",h4:"h4"},n.components);return(0,s.jsxs)(s.Fragment,{children:[(0,s.jsxs)(l.h1,{id:"\u79FB\u52A8\u7AEF\u5E03\u5C40",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u79FB\u52A8\u7AEF\u5E03\u5C40",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u79FB\u52A8\u7AEF\u5E03\u5C40"]}),`
`,(0,s.jsxs)(l.p,{children:["alita \u5185\u7F6E ",(0,s.jsx)(l.code,{children:"plugin-mobile-layout"})," \u63D2\u4EF6\u63D0\u4F9B\u4E86\u4E00\u4E2A\u9875\u9762\u5934\u90E8\u6709\u5BFC\u822A\u680F\uFF0C\u9875\u9762\u5E95\u90E8\u6709\u5BFC\u822A\u6807\u7B7E\u680F\u7684\u5E03\u5C40\u3002\u5176\u4E2D\u4F7F\u7528\u5230 antd-mobile \u4E2D\u7684 ",(0,s.jsx)(l.code,{children:"NavBar"}),"\u3001",(0,s.jsx)(l.code,{children:"TabBar"}),"\u7EC4\u4EF6\u3002"]}),`
`,(0,s.jsxs)(l.p,{children:["\u8FD8\u4F1A\u81EA\u52A8\u68C0\u6D4B\u9879\u76EE\u4E2D\u5B89\u88C5\u7684 antd-mobile \u7248\u672C\uFF0C\u81EA\u52A8\u5207\u6362\u5230 ",(0,s.jsx)(l.code,{children:"antd-mobile@2.3.4"})," \u6216\u8005 ",(0,s.jsx)(l.code,{children:"antd-mobile@^5"}),"\u3002"]}),`
`,(0,s.jsxs)(l.h2,{id:"\u914D\u7F6E",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u914D\u7F6E",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u914D\u7F6E"]}),`
`,(0,s.jsxs)(l.p,{children:["\u5728 ",(0,s.jsx)(l.code,{children:"config/config.ts"})," \u4E2D\u914D\u7F6E ",(0,s.jsx)(l.code,{children:"mobileLayout:'mobile5'"})," \u5F00\u542F\uFF0C\u5E76\u8BBE\u7F6E antd-mobile \u7248\u672C\u3002"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"defineConfig"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"defineConfig"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"appType:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'h5'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"mobileLayout:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'mobile5'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u8BBE\u7F6E antd-mobile \u7248\u672C"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"});"})})]})})}),`
`,(0,s.jsxs)(l.h2,{id:"\u8FD0\u884C\u65F6\u7684\u914D\u7F6E",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u8FD0\u884C\u65F6\u7684\u914D\u7F6E",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u8FD0\u884C\u65F6\u7684\u914D\u7F6E"]}),`
`,(0,s.jsxs)(l.p,{children:["\u53EF\u4EE5\u5728 ",(0,s.jsx)(l.code,{children:"src/app.ts"})," \u4E2D\u914D\u7F6E\u9875\u9762\u5E95\u90E8\u5BFC\u822A\u6807\u7B7E\u680F\u3001\u6240\u6709\u9875\u9762\u7684\u9ED8\u8BA4 title\u3001\u9875\u9762\u7684 title\u3001\u9875\u9762\u5934\u90E8\u5BFC\u822A\u680F\u3002"]}),`
`,(0,s.jsxs)(l.p,{children:["\u901A\u8FC7 export ",(0,s.jsx)(l.code,{children:"mobileLayout"})," \u5BF9\u8C61\u5C06\u4F5C\u4E3A\u914D\u7F6E\u4F20\u9012\u7ED9 alita \u79FB\u52A8\u7AEF\u5E03\u5C40\u7EC4\u4EF6\uFF0C\u5982\u4E0B\u6240\u793A\uFF1A"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"mobileLayout"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"tabBar"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"navBar"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"documentTitle:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u9ED8\u8BA4\u6807\u9898'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"titleList"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`,(0,s.jsxs)(l.table,{children:[(0,s.jsx)(l.thead,{children:(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.th,{children:"\u5C5E\u6027"}),(0,s.jsx)(l.th,{children:"\u7C7B\u578B"}),(0,s.jsx)(l.th,{children:"\u5FC5\u586B"}),(0,s.jsx)(l.th,{children:"\u63CF\u8FF0"})]})}),(0,s.jsxs)(l.tbody,{children:[(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"tabBar"}),(0,s.jsx)(l.td,{children:"TabBarProps"}),(0,s.jsx)(l.td,{children:"\u5426"}),(0,s.jsx)(l.td,{children:"\u5B9A\u4E49\u9875\u9762\u5E95\u90E8\u5BFC\u822A\u6807\u7B7E\u680F"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"navBar"}),(0,s.jsx)(l.td,{children:"NavBarProps"}),(0,s.jsx)(l.td,{children:"\u5426"}),(0,s.jsx)(l.td,{children:"\u5B9A\u4E49\u9875\u9762\u5934\u90E8\u5BFC\u822A\u680F"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"documentTitle"}),(0,s.jsx)(l.td,{children:"string"}),(0,s.jsx)(l.td,{children:"\u5426"}),(0,s.jsx)(l.td,{children:"\u5B9A\u4E49\u6240\u6709\u9875\u9762\u7684\u9ED8\u8BA4\u6807\u9898"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"titleList"}),(0,s.jsx)(l.td,{children:"TitleListItem[]"}),(0,s.jsx)(l.td,{children:"\u5426"}),(0,s.jsx)(l.td,{children:"\u5B9A\u4E49\u9875\u9762\u7684\u6807\u9898"})]})]})]}),`
`,(0,s.jsxs)(l.h3,{id:"\u5B9A\u4E49\u9875\u9762\u5E95\u90E8\u5BFC\u822A\u6807\u7B7E\u680F",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u5B9A\u4E49\u9875\u9762\u5E95\u90E8\u5BFC\u822A\u6807\u7B7E\u680F",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u5B9A\u4E49\u9875\u9762\u5E95\u90E8\u5BFC\u822A\u6807\u7B7E\u680F"]}),`
`,(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"tabBar"})," \u7684\u7C7B\u578B ",(0,s.jsx)(l.code,{children:"TabBarProps"})," \u5B9A\u4E49\u5982\u4E0B\uFF1A"]}),`
`,(0,s.jsxs)(l.table,{children:[(0,s.jsx)(l.thead,{children:(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.th,{children:"\u5C5E\u6027"}),(0,s.jsx)(l.th,{children:"\u7C7B\u578B"}),(0,s.jsx)(l.th,{children:"\u5FC5\u586B"}),(0,s.jsx)(l.th,{children:"\u63CF\u8FF0"})]})}),(0,s.jsxs)(l.tbody,{children:[(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"color"}),(0,s.jsx)(l.td,{children:"HexColor"}),(0,s.jsx)(l.td,{children:"\u662F"}),(0,s.jsx)(l.td,{children:"\u5BFC\u822A\u6807\u7B7E\u7684\u6587\u5B57\u9ED8\u8BA4\u989C\u8272\uFF0C\u4EC5\u652F\u6301\u5341\u516D\u8FDB\u5236\u989C\u8272"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"selectedColor"}),(0,s.jsx)(l.td,{children:"HexColor"}),(0,s.jsx)(l.td,{children:"\u662F"}),(0,s.jsx)(l.td,{children:"\u5BFC\u822A\u6807\u7B7E\u7684\u6587\u5B57\u9009\u4E2D\u65F6\u7684\u989C\u8272\uFF0C\u4EC5\u652F\u6301\u5341\u516D\u8FDB\u5236\u989C\u8272"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"backgroundColor"}),(0,s.jsx)(l.td,{children:"HexColor"}),(0,s.jsx)(l.td,{children:"\u662F"}),(0,s.jsx)(l.td,{children:"\u5BFC\u822A\u6807\u7B7E\u7684\u80CC\u666F\u8272\uFF0C\u4EC5\u652F\u6301\u5341\u516D\u8FDB\u5236\u989C\u8272"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"list"}),(0,s.jsx)(l.td,{children:"TabBarListItem[]"}),(0,s.jsx)(l.td,{children:"\u662F"}),(0,s.jsx)(l.td,{children:"\u5BFC\u822A\u6807\u7B7E\u7684\u5217\u8868\uFF0C\u6700\u5C11 2 \u4E2A\u3001\u6700\u591A 5 \u4E2A tab"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"tabsGroup"}),(0,s.jsx)(l.td,{children:"string[][]"}),(0,s.jsx)(l.td,{children:"\u5426"}),(0,s.jsx)(l.td,{children:"\u5F53\u9700\u8981\u591A\u5957 tabBar \u65F6\u914D\u7F6E"})]})]})]}),`
`,(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"tabBar.list"})," \u7684\u7C7B\u578B ",(0,s.jsx)(l.code,{children:"TabBarListItem"})," \u5B9A\u4E49\u5982\u4E0B\uFF1A"]}),`
`,(0,s.jsxs)(l.table,{children:[(0,s.jsx)(l.thead,{children:(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.th,{children:"\u5C5E\u6027"}),(0,s.jsx)(l.th,{children:"\u7C7B\u578B"}),(0,s.jsx)(l.th,{children:"\u5FC5\u586B"}),(0,s.jsx)(l.th,{children:"\u8BF4\u660E"})]})}),(0,s.jsxs)(l.tbody,{children:[(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"pagePath"}),(0,s.jsx)(l.td,{children:"string"}),(0,s.jsx)(l.td,{children:"\u662F"}),(0,s.jsx)(l.td,{children:"\u9875\u9762\u8DEF\u5F84\uFF0C\u5FC5\u987B\u5728 pages \u4E2D\u5148\u5B9A\u4E49"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"text"}),(0,s.jsx)(l.td,{children:"string"}),(0,s.jsx)(l.td,{children:"\u5426"}),(0,s.jsx)(l.td,{children:"\u5BFC\u822A\u6807\u7B7E\u7684\u6587\u5B57"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"iconPath"}),(0,s.jsx)(l.td,{children:"string"}),(0,s.jsx)(l.td,{children:"\u5426"}),(0,s.jsx)(l.td,{children:"\u5BFC\u822A\u6807\u7B7E\u56FE\u6807\u8DEF\u5F84"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"selectedIconPath"}),(0,s.jsx)(l.td,{children:"string"}),(0,s.jsx)(l.td,{children:"\u5426"}),(0,s.jsx)(l.td,{children:"\u5BFC\u822A\u6807\u7B7E\u9009\u4E2D\u65F6\u7684\u56FE\u6807\u8DEF\u5F84"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"iconSize"}),(0,s.jsx)(l.td,{children:"string"}),(0,s.jsx)(l.td,{children:"\u5426"}),(0,s.jsx)(l.td,{children:"0.44rem\u300120px"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"badge"}),(0,s.jsx)(l.td,{children:"string"}),(0,s.jsx)(l.td,{children:"\u5426"}),(0,s.jsx)(l.td,{children:"\u5BFC\u822A\u6807\u7B7E\u56FE\u6807\u53F3\u4E0A\u89D2\u663E\u793A\u6570\u503C \uFF08\u5FAE\u6807\u6570\uFF09"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"onPress"}),(0,s.jsx)(l.td,{children:"function"}),(0,s.jsx)(l.td,{children:"\u5426"}),(0,s.jsx)(l.td,{children:"\u5BFC\u822A\u6807\u7B7E\u70B9\u51FB\u56DE\u8C03"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"title"}),(0,s.jsx)(l.td,{children:"string"}),(0,s.jsx)(l.td,{children:"\u5426"}),(0,s.jsx)(l.td,{children:"\u9875\u9762\u6807\u9898"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"icon"}),(0,s.jsx)(l.td,{children:"ReactNode"}),(0,s.jsx)(l.td,{children:"\u5426"}),(0,s.jsx)(l.td,{children:"\u81EA\u5B9A\u4E49\u5BFC\u822A\u6807\u7B7E"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"selectedIcon"}),(0,s.jsx)(l.td,{children:"ReactNode"}),(0,s.jsx)(l.td,{children:"\u5426"}),(0,s.jsx)(l.td,{children:"\u81EA\u5B9A\u4E49\u9009\u4E2D\u7684\u5BFC\u822A\u6807\u7B7E"})]})]})]}),`
`,(0,s.jsx)(l.p,{children:"\u793A\u4F8B\uFF1A"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"history"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"type"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"TabBarProps"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"TabBarListItem"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"AppstoreOutline"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"FileOutline"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'antd-mobile-icons'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"tabList"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"TabBarListItem"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"[] = ["})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  {"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pagePath:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"text:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u9996\u9875'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"icon:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"AppstoreOutline"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" />,"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"selectedIcon:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"AppstoreOutline"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" />,"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"iconSize:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'20px'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"title:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u9996\u9875'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"onPress"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" () "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"{"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"history"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"replace"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  },"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  {"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pagePath:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/list'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"text:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u5F85\u529E'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"icon:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"FileOutline"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" />,"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"selectedIcon:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"FileOutline"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" />,"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"iconSize:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'20px'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"title:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u5F85\u529E\u4E2D\u5FC3'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"badge:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'3'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"onPress:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" () = {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      history.replace("}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/list'"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:")"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"    }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"  },"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"] "})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"const tabBar:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"TabBarProps"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"color:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"`#000000`"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"selectedColor:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'#00A0FF'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"backgroungColor:"}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'#Fff'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"list:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"tabList"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"tabsGroup:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"[["}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/list'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"],["}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/new'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/ad'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"]]"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"mobileLayout"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"tabBar"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"\u5B9A\u4E49\u9875\u9762\u5934\u90E8\u5BFC\u822A\u680F",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u5B9A\u4E49\u9875\u9762\u5934\u90E8\u5BFC\u822A\u680F",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u5B9A\u4E49\u9875\u9762\u5934\u90E8\u5BFC\u822A\u680F"]}),`
`,(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"navBar"})," \u7684\u7C7B\u578B ",(0,s.jsx)(l.code,{children:"NavBarProps"})," \u5B9A\u4E49\u5982\u4E0B\uFF1A"]}),`
`,(0,s.jsxs)(l.table,{children:[(0,s.jsx)(l.thead,{children:(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.th,{children:"\u5C5E\u6027"}),(0,s.jsx)(l.th,{children:"\u8BF4\u660E"}),(0,s.jsx)(l.th,{children:"\u7C7B\u578B"}),(0,s.jsx)(l.th,{children:"\u9ED8\u8BA4\u503C"})]})}),(0,s.jsxs)(l.tbody,{children:[(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"mode"}),(0,s.jsx)(l.td,{children:"\u98CE\u683C\u6A21\u5F0F"}),(0,s.jsx)(l.td,{children:"string"}),(0,s.jsxs)(l.td,{children:["'dark' enum","light"]})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"icon"}),(0,s.jsx)(l.td,{children:"\u5934\u90E8\u5BFC\u822A\u5DE6\u4FA7\uFF0C\u8FD4\u56DE\u533A\u57DF\u7684\u56FE\u6807"}),(0,s.jsx)(l.td,{children:"ReactNode"}),(0,s.jsx)(l.td,{children:"\u4E0D\u5728 tabsBar \u4E2D\u5B9A\u4E49\u7684\u9875\u9762\uFF0C\u4F1A\u6709\u9ED8\u8BA4\u5DE6\u8FD4\u56DE\u56FE\u6807"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"leftContent"}),(0,s.jsx)(l.td,{children:"\u5934\u90E8\u5BFC\u822A\u5DE6\u4FA7\u7684\u8FD4\u56DE\u533A\u57DF\u7684\u53F3\u4FA7\u5185\u5BB9"}),(0,s.jsx)(l.td,{children:"React.ReactNode"}),(0,s.jsx)(l.td,{children:"\u65E0"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"rightContent"}),(0,s.jsx)(l.td,{children:"\u5934\u90E8\u5BFC\u822A\u53F3\u4FA7\u5185\u5BB9"}),(0,s.jsx)(l.td,{children:"React.ReactNode"}),(0,s.jsx)(l.td,{children:"\u65E0"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"onLeftClick"}),(0,s.jsx)(l.td,{children:"\u5934\u90E8\u5BFC\u822A\u5DE6\u4FA7\u7684\u8FD4\u56DE\u533A\u57DF\u70B9\u51FB\u56DE\u8C03"}),(0,s.jsx)(l.td,{children:"(navigate) => void"}),(0,s.jsx)(l.td,{children:"\u6709\u5DE6\u4FA7\u56DE\u9000\u56FE\u6807\u7684\u9ED8\u8BA4\u4E8B\u4EF6\u662F\u8FD4\u56DE\u4E0A\u4E00\u9875"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"navList"}),(0,s.jsx)(l.td,{children:"\u5355\u72EC\u8BBE\u7F6E\u67D0\u4E9B\u9875\u9762\u7684 navbar"}),(0,s.jsx)(l.td,{children:"NarBarListItem"}),(0,s.jsx)(l.td,{children:"\u65E0"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"hideNavBar"}),(0,s.jsx)(l.td,{children:"\u9690\u85CF NavBar\uFF0C\u9ED8\u8BA4\u6709 NarBar"}),(0,s.jsx)(l.td,{children:"boolean"}),(0,s.jsx)(l.td,{children:"false"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"pageBackground"}),(0,s.jsx)(l.td,{children:"\u9875\u9762\u7684\u80CC\u666F\u989C\u8272"}),(0,s.jsx)(l.td,{children:"string"}),(0,s.jsx)(l.td,{children:"'#FFF'"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"pageTitle"}),(0,s.jsx)(l.td,{children:"\u9875\u9762\u6807\u9898"}),(0,s.jsx)(l.td,{children:"string"}),(0,s.jsx)(l.td,{children:"\u65E0\uFF0C\u4F18\u5148\u7EA7\u6700\u9AD8"})]})]})]}),`
`,(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"navList"})," \u7684\u7C7B\u578B ",(0,s.jsx)(l.code,{children:"NarBarListItem"})," \u5B9A\u4E49\u5982\u4E0B\uFF1A"]}),`
`,(0,s.jsxs)(l.table,{children:[(0,s.jsx)(l.thead,{children:(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.th,{children:"\u5C5E\u6027"}),(0,s.jsx)(l.th,{children:"\u7C7B\u578B"}),(0,s.jsx)(l.th,{children:"\u9ED8\u8BA4\u503C"}),(0,s.jsx)(l.th,{children:"\u8BF4\u660E"})]})}),(0,s.jsxs)(l.tbody,{children:[(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"pagePath"}),(0,s.jsx)(l.td,{children:"string"}),(0,s.jsx)(l.td,{children:"\u65E0"}),(0,s.jsx)(l.td,{children:"\u9875\u9762\u8DEF\u5F84\uFF0C\u5FC5\u987B\u5728 pages \u4E2D\u5148\u5B9A\u4E49"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"navBar"}),(0,s.jsx)(l.td,{children:"NavBarProps"}),(0,s.jsx)(l.td,{children:"\u65E0"}),(0,s.jsx)(l.td,{children:"\u5F53\u524D\u8DEF\u7531\u7684 navBar"})]})]})]}),`
`,(0,s.jsx)(l.p,{children:"\u793A\u4F8B\uFF1A"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"type"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"NavBarProps"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"NavBarListItem"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"LeftOutline"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'antd-mobile-icons'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"navList"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"NavBarListItem"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"[] = ["})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  {"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pagePath:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/list'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"navBar:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"mode:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'dark'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"icon:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"LeftOutline"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" />,"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"rightContent:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" (<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"\u8BE6\u60C5"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">),"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"onLeftClick"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"navigate"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"navigate"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"(-"}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      },"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pageBackground:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'#fff'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pageTitle:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u5F85\u529E\u4E2D\u5FC3'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    },"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  },"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  {"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pagePath:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/details'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"navBar:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"hideNavBar:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"false"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"];"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"navBar"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"NavBarProps"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"mode:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'dark'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"onLeftClick"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"navigate"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"navigate"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"(-"}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  },"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pageBackground:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'#fff'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pageTitle:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u9996\u9875'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"navList"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"mobileLayout"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"navBar"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"\u5B9A\u4E49\u9875\u9762\u7684\u6807\u9898",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u5B9A\u4E49\u9875\u9762\u7684\u6807\u9898",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u5B9A\u4E49\u9875\u9762\u7684\u6807\u9898"]}),`
`,(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"titleList"})," \u7684\u7C7B\u578B ",(0,s.jsx)(l.code,{children:"TitleListItem[]"})," \u5B9A\u4E49\u5982\u4E0B\uFF1A"]}),`
`,(0,s.jsxs)(l.table,{children:[(0,s.jsx)(l.thead,{children:(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.th,{children:"\u5C5E\u6027"}),(0,s.jsx)(l.th,{children:"\u7C7B\u578B"}),(0,s.jsx)(l.th,{children:"\u5FC5\u586B"}),(0,s.jsx)(l.th,{children:"\u8BF4\u660E"})]})}),(0,s.jsxs)(l.tbody,{children:[(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"pagePath"}),(0,s.jsx)(l.td,{children:"string"}),(0,s.jsx)(l.td,{children:"\u662F"}),(0,s.jsx)(l.td,{children:"\u9875\u9762\u8DEF\u5F84\uFF0C\u5FC5\u987B\u5728 pages \u4E2D\u5148\u5B9A\u4E49"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{children:"title"}),(0,s.jsx)(l.td,{children:"string"}),(0,s.jsx)(l.td,{children:"\u5426"}),(0,s.jsx)(l.td,{children:"\u9875\u9762\u6807\u9898"})]})]})]}),`
`,(0,s.jsx)(l.p,{children:"\u793A\u4F8B\uFF1A"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"type"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"TitleListItem"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"LeftOutline"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'antd-mobile-icons'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"titleList"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"TitleListItem"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"[] = ["})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  {"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pagePath:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"title:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u9996\u9875'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  },"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"];"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"mobileLayout"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"titleList"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"\u5B9A\u4E49\u6240\u6709\u9875\u9762\u7684\u9ED8\u8BA4\u6807\u9898",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u5B9A\u4E49\u6240\u6709\u9875\u9762\u7684\u9ED8\u8BA4\u6807\u9898",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u5B9A\u4E49\u6240\u6709\u9875\u9762\u7684\u9ED8\u8BA4\u6807\u9898"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"mobileLayout"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"documentTitle:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u9ED8\u8BA4\u6807\u9898'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`,(0,s.jsxs)(l.h4,{id:"\u9875\u9762\u6807\u9898\u7684\u8BBE\u7F6E\u4F18\u5148\u7EA7",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u9875\u9762\u6807\u9898\u7684\u8BBE\u7F6E\u4F18\u5148\u7EA7",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u9875\u9762\u6807\u9898\u7684\u8BBE\u7F6E\u4F18\u5148\u7EA7"]}),`
`,(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"titleList"})," \u7684 ",(0,s.jsx)(l.code,{children:"title"}),"> ",(0,s.jsx)(l.code,{children:"tabBar"})," \u4E2D ",(0,s.jsx)(l.code,{children:"list"})," \u7684 ",(0,s.jsx)(l.code,{children:"title"})," > ",(0,s.jsx)(l.code,{children:"documentTitle"}),"\u3002"]}),`
`,(0,s.jsxs)(l.h2,{id:"\u52A8\u6001\u914D\u7F6E",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u52A8\u6001\u914D\u7F6E",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u52A8\u6001\u914D\u7F6E"]}),`
`,(0,s.jsxs)(l.p,{children:["\u901A\u8FC7 alita \u5185\u7F6E ",(0,s.jsx)(l.code,{children:"plugin-mobile-layout"})," \u63D2\u4EF6\u63D0\u4F9B\u7684 ",(0,s.jsx)(l.a,{href:"../api/layout-api#setpagenavbar",children:(0,s.jsx)(l.code,{children:"setPageNavBar"})})," \u6765\u914D\u7F6E\u9875\u9762\u5934\u90E8\u5BFC\u822A\u680F\uFF0C",(0,s.jsx)(l.a,{href:"../api/layout-api#setTabBarList",children:(0,s.jsx)(l.code,{children:"setTabBarList"})})," \u6765\u914D\u7F6E\u9875\u9762\u5E95\u90E8\u5BFC\u822A\u6807\u7B7E\u680F\u3002"]})]})}}c.default=h}}]);
