"use strict";(self.webpackChunkalita3=self.webpackChunkalita3||[]).push([[933],{51591:function(x,r,e){e.r(r);var D=e(57213),a=e.n(D),d=e(93236),s=e(62086);function t(){var n=arguments.length>0&&arguments[0]!==void 0?arguments[0]:{};(0,d.useEffect)(function(){var l;if(window.location.hash.length!==0){var p=decodeURIComponent(window.location.hash);setTimeout(function(){var c;(c=document.getElementById(p.slice(1)))===null||c===void 0||c.scrollIntoView()},100)}else window.scrollTo(0,0);(l=document.getElementById("active-nav-item"))===null||l===void 0||l.scrollIntoView({behavior:"smooth",block:"center"})},[]);var h=n.components||{},o=h.wrapper;return o?(0,s.jsx)(o,a()(a()({},n),{},{children:(0,s.jsx)(i,{})})):i();function i(){var l=Object.assign({h1:"h1",a:"a",span:"span",h2:"h2",p:"p",code:"code",div:"div",pre:"pre",h3:"h3",blockquote:"blockquote",h4:"h4",ul:"ul",li:"li"},n.components);return(0,s.jsxs)(s.Fragment,{children:[(0,s.jsxs)(l.h1,{id:"\u591A-tabs-\u5B9E\u9A8C\u6027",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u591A-tabs-\u5B9E\u9A8C\u6027",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u591A Tabs \uFF08\u5B9E\u9A8C\u6027\uFF09"]}),`
`,(0,s.jsxs)(l.h2,{id:"\u5F00\u59CB\u4F7F\u7528",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u5F00\u59CB\u4F7F\u7528",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u5F00\u59CB\u4F7F\u7528"]}),`
`,(0,s.jsxs)(l.p,{children:["\u914D\u7F6E ",(0,s.jsx)(l.code,{children:"tabsLayout"})," \u5F00\u542F"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// config/config.ts"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"tabsLayout:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { },"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`,(0,s.jsxs)(l.h2,{id:"\u914D\u7F6E",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u914D\u7F6E",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u914D\u7F6E"]}),`
`,(0,s.jsxs)(l.h3,{id:"\u6784\u5EFA\u65F6\u914D\u7F6E",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u6784\u5EFA\u65F6\u914D\u7F6E",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u6784\u5EFA\u65F6\u914D\u7F6E"]}),`
`,(0,s.jsxs)(l.blockquote,{children:[`
`,(0,s.jsx)(l.p,{children:"config/config.ts \u4E2D\u914D\u7F6E tabsLayout"}),`
`]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"defineConfig"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"defineConfig"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"layout:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"hasCustomTabs:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Joi"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"boolean"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"(),"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"hasDropdown:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Joi"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"boolean"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"(),"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"hasFixedHeader:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Joi"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"boolean"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"()"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  },"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"});"})})]})})}),`
`,(0,s.jsxs)(l.h4,{id:"hascustomtabs",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#hascustomtabs",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"hasCustomTabs"]}),`
`,(0,s.jsxs)(l.p,{children:["\u662F\u5426\u4F7F\u7528\u81EA\u5B9A\u4E49\u7684 tabs \u7EC4\u4EF6\uFF0C\u9700\u8981\u642D\u914D\u8FD0\u884C\u65F6\u914D\u7F6E ",(0,s.jsx)(l.code,{children:"getCustomTabs"})," \u4F7F\u7528(\u8BE6\u89C1\u4E0B\u65B9\u8FD0\u884C\u65F6\u914D\u7F6E\u8BF4\u660E)"]}),`
`,(0,s.jsxs)(l.h4,{id:"hasdropdown",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#hasdropdown",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"hasDropdown"]}),`
`,(0,s.jsx)(l.p,{children:"\u662F\u5426\u5F00\u542F\u53F3\u4FA7\u7684 tabs \u7BA1\u7406\u5668\uFF0C\u53EF\u4EE5\u5B9E\u73B0\u201C\u5173\u95ED\u5DE6\u4FA7\u201D\uFF0C\u201C\u5173\u95ED\u53F3\u4FA7\u201D\uFF0C\u201C\u5173\u95ED\u5176\u4ED6\u201D\u548C\u201C\u5237\u65B0\u201D\u7B49\u529F\u80FD\u3002"}),`
`,(0,s.jsxs)(l.h4,{id:"hasfixedheader",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#hasfixedheader",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"hasFixedHeader"]}),`
`,(0,s.jsx)(l.p,{children:"\u662F\u5426\u5F00\u542F tabs \u5934\u90E8\u5B9A\u4F4D"}),`
`,(0,s.jsxs)(l.ul,{children:[`
`,(0,s.jsxs)(l.li,{children:["\u9ED8\u8BA4\u9002\u914D ",(0,s.jsx)(l.a,{href:"https://procomponents.ant.design/components/layout/",children:"ProLayout"})," \u5E03\u5C40"]}),`
`,(0,s.jsxs)(l.li,{children:["\u5982\u679C\u4F7F\u7528 ant-design \u4F5C\u4E3Aui\u5E93\uFF0C\u5219\u9700\u8981\u786E\u4FDDlayout\u4E2D header\u3001slider \u56FA\u5B9A\uFF0Ccontent \u6EDA\u52A8\uFF0C\u8BE6\u89C1 ",(0,s.jsx)(l.a,{href:"https://github.com/alitajs/alita/blob/master/examples/tabs/src/layouts/index.tsx",children:"Demo"})]}),`
`]}),`
`,(0,s.jsxs)(l.h3,{id:"\u8FD0\u884C\u65F6\u914D\u7F6E",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u8FD0\u884C\u65F6\u914D\u7F6E",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u8FD0\u884C\u65F6\u914D\u7F6E"]}),`
`,(0,s.jsxs)(l.blockquote,{children:[`
`,(0,s.jsx)(l.p,{children:"src/app.ts \u4E2D\u914D\u7F6E"}),`
`]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"tsx","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"tsx","data-theme":"default",children:[(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Tabs"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"message"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"} "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'antd'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"EllipsisOutlined"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"@ant-design/icons"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"TabPane"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } = "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Tabs"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"tabsLayout"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"initialState"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}) {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5982\u679C\u548C initialState \u63D2\u4EF6\u642D\u914D\u4F7F\u7528\u7684\u65F6\u5019\uFF0C\u4F1A\u4F20\u5165 initialState\uFF0C\u5426\u5219 initialState \u6C38\u8FDC\u4E3A\u7A7A"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"local:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/'"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u9996\u9875'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/users'"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u7528\u6237'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/foo'"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u5176\u4ED6'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    },"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"icon:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/users'"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"UserOutlined"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"/>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    },"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5176\u4ED6 antd Tabs \u5C5E\u6027"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"size:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'large'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"onTabClick"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"key"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"console"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"log"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"key"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    },"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  };"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"getCustomTabs"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = () "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ({"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"isKeep"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"keepElements"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"navigate"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"dropByCacheKey"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"local"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"activeKey"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }: "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"any"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"className"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"rumtime-keep-alive-tabs-layout"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"hidden"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"{"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"!"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"isKeep"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"}"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Tabs"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"          "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"hideAdd"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"          "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"onChange"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"{"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"key"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"            "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"navigate"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"key"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"          }"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"}"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"          "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"activeKey"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"{"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"activeKey"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"}"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"          "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"type"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"editable-card"'})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"          "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"onEdit"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"{"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"targetKey"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"            "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"pathList"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Object"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"keys"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"keepElements"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"current"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:")"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"            "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"if"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pathList"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"length"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" === "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"              "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"message"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"info"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u81F3\u5C11\u8981\u4FDD\u7559\u4E00\u4E2A\u7A97\u53E3'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:")"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"              "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"            }"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"            "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"dropByCacheKey"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"targetKey"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:")"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"            "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"if"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"targetKey"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" === "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"activeKey"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"              "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5220\u9664\u5F53\u524D\u9009\u4E2D\u7684tab\u65F6:"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"              "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// 1.\u5982\u679C\u5F53\u524Dtab\u662F\u7B2C\u4E00\u4E2A\u65F6\u81EA\u52A8\u9009\u4E2D\u540E\u4E00\u4E2A"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"              "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// 2.\u4E0D\u662F\u7B2C\u4E00\u4E2A\u65F6\u81EA\u52A8\u9009\u4E2D\u524D\u4E00\u4E2A"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"              "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"i"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pathList"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"indexOf"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"targetKey"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:")"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"              "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"navigate"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pathList"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"["}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"i"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" === "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"0"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ? "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"i"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" + "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" : "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"i"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" - "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"])"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"            }"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"          }"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"}"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"          "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"{"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Object"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"entries"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"keepElements"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"current"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:")."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"map"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"            (["}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pathname"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"element"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"]: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"any"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"              "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"TabPane"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"tab"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"{"}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"`"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"${"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"local"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"["}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pathname"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"] || "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pathname"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"}"}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"`"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"}"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"key"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"{"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pathname"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"}"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"/>"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"            ),"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"          )"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"}"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Tabs"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    );"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  };"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "})]})})}),`
`,(0,s.jsxs)(l.h4,{id:"tabslayout",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#tabslayout",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"tabsLayout"]}),`
`,(0,s.jsxs)(l.blockquote,{children:[`
`,(0,s.jsx)(l.p,{children:"\u5982\u679C\u548C initialState \u63D2\u4EF6\u642D\u914D\u4F7F\u7528\u7684\u65F6\u5019\uFF0CtabsLayout \u51FD\u6570\u4F1A\u4F20\u5165\u771F\u5B9E\u7684 initialState\uFF0C\u5426\u5219 initialState \u6C38\u8FDC\u4E3A\u7A7A"}),`
`]}),`
`,(0,s.jsx)(l.p,{children:"tabsLayout \u8FD4\u56DE\u4E00\u4E2A\u5BF9\u8C61\uFF0C\u9664\u4E86 icon \u548C local \u4E3A\u591ATabs\u76F8\u5173\u529F\u80FD\u4F7F\u7528\uFF0C\u5269\u4F59\u7684\u5C5E\u6027\u4F1A\u900F\u4F20\u5230 Tabs \u4E0A\uFF0C\u4F60\u53EF\u4EE5\u5728\u8FD9\u91CC\u8BBE\u7F6E Tabs\u3002"}),`
`,(0,s.jsxs)(l.h4,{id:"getcustomtabs",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#getcustomtabs",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"getCustomTabs"]}),`
`,(0,s.jsxs)(l.p,{children:["\u5B8C\u5168\u8986\u76D6\u5185\u7F6E\u7684\u591A Tabs \u7EC4\u4EF6\uFF0C\u9700\u8981\u642D\u914D\u914D\u7F6E ",(0,s.jsx)(l.code,{children:"hasCustomTabs:true"})," \u4F7F\u7528\u3002"]}),`
`,(0,s.jsxs)(l.h2,{id:"api",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#api",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"API"]}),`
`,(0,s.jsxs)(l.h3,{id:"keepalivecontext",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#keepalivecontext",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"KeepAliveContext"]}),`
`,(0,s.jsx)(l.p,{children:"\u53EF\u4EE5\u4ECE alita \u4E2D\u627E\u5230 KeepAliveContext \u4E0A\u4E0B\u6587\u3002"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"KeepAliveContext"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" () "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {  } = "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useContext"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"KeepAliveContext"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  );"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`,(0,s.jsxs)(l.h4,{id:"dropbycachekey",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#dropbycachekey",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"dropByCacheKey"]}),`
`,(0,s.jsx)(l.p,{children:"\u6E05\u7A7A\u5F53\u524D\u9875\u9762\u7684\u72B6\u6001\u4FDD\u6301\uFF0C\u5176\u5B9E\u4E5F\u5C31\u662F\u5237\u65B0\u9875\u9762\u3002"}),`
`,(0,s.jsx)(l.p,{children:"\u4F7F\u7528\u65B9\u6CD5"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"dropByCacheKey"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita || umi || @umijs/max'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"dropByCacheKey"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pathname"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]})]})})}),`
`,(0,s.jsxs)(l.h4,{id:"closetab",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#closetab",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"closeTab"]}),`
`,(0,s.jsx)(l.p,{children:"\u5173\u95ED\u67D0\u4E2A\u9875\u9762"}),`
`,(0,s.jsx)(l.p,{children:"\u4F7F\u7528\u65B9\u6CD5"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"closeTab"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita || umi || @umijs/max'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"closeTab"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pathname"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]})]})})}),`
`,(0,s.jsxs)(l.h4,{id:"updatetab",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#updatetab",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"updateTab"]}),`
`,(0,s.jsx)(l.p,{children:"\u66F4\u65B0\u5F53\u524D tab \u7684\u5C5E\u6027\u3002\u53EF\u4EE5\u7528\u4E8E\u900F\u4F20\u53C2\u6570\u5230 TabPane \u7EC4\u4EF6\u4E0A\u3002"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"TabPaneProps"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'antd'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"interface"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"TabConfig"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"extends"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"TabPaneProps"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"{"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"icon"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"ReactNode"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"name"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"closable"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"boolean"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"updateTab"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"path"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"config"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"TabConfig"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"void"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]})]})})}),`
`,(0,s.jsx)(l.p,{children:"\u4F7F\u7528\u65B9\u6CD5"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"KeepAliveContext"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"useLocation"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"useParams"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" () "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"location"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useLocation"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"updateTab"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } = "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useContext"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"KeepAliveContext"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"params"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useParams"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useEffect"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"(() "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"updateTab"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"location"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pathname"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"name:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u8BE6\u60C5'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" + "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"params"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"index"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"closeIcon:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"UserOutlined"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"/>,"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    });"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }, []);"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"handleClick"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = () "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"updateTab"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"location"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pathname"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"icon:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"UserOutlined"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" />,"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"name:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'hahaha'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" + "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Math"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"ceil"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"(("}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Math"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"random"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"() * "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"100"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") / "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"10"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"),"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"closable:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"false"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    });"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  };"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  );"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "})]})})}),`
`,(0,s.jsxs)(l.h4,{id:"\u5176\u4ED6\u4E0D\u5E38\u7528",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u5176\u4ED6\u4E0D\u5E38\u7528",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u5176\u4ED6\u4E0D\u5E38\u7528"]}),`
`,(0,s.jsxs)(l.p,{children:["\u4F7F\u7528\u65B9\u6CD5\u540C updateTab \uFF0C\u90FD\u662F\u4ECE ",(0,s.jsx)(l.code,{children:"React.useContext(KeepAliveContext);"})," \u53D6\u51FA"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5173\u95ED\u5DE6\u4FA7 tabs"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C8C8C8"},children:"dropLeftTabs"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"path"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"void"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5173\u95ED\u53F3\u4FA7 tabs"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C8C8C8"},children:"dropRightTabs"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"path"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"void"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5173\u95ED\u5176\u4ED6"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C8C8C8"},children:"dropOtherTabs"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"path"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"void"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5237\u65B0"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C8C8C8"},children:"refreshTab"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"path"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"void"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]})]})})})]})}}r.default=t}}]);
