"use strict";(self.webpackChunkalita3=self.webpackChunkalita3||[]).push([[875],{24448:function(x,c,l){l.r(c);var d=l(57213),o=l.n(d),t=l(93236),s=l(62086);function D(){var n=arguments.length>0&&arguments[0]!==void 0?arguments[0]:{};(0,t.useEffect)(function(){var e;if(window.location.hash.length!==0){var p=decodeURIComponent(window.location.hash);setTimeout(function(){var r;(r=document.getElementById(p.slice(1)))===null||r===void 0||r.scrollIntoView()},100)}else window.scrollTo(0,0);(e=document.getElementById("active-nav-item"))===null||e===void 0||e.scrollIntoView({behavior:"smooth",block:"center"})},[]);var h=n.components||{},a=h.wrapper;return a?(0,s.jsx)(a,o()(o()({},n),{},{children:(0,s.jsx)(i,{})})):i();function i(){var e=Object.assign({h1:"h1",a:"a",span:"span",p:"p",code:"code",h2:"h2",div:"div",pre:"pre",h3:"h3",h4:"h4",ul:"ul",li:"li"},n.components);return(0,s.jsxs)(s.Fragment,{children:[(0,s.jsxs)(e.h1,{id:"\u8BF7\u6C42",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u8BF7\u6C42",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u8BF7\u6C42"]}),`
`,(0,s.jsxs)(e.p,{children:["\u57FA\u4E8E ",(0,s.jsx)(e.a,{href:"https://github.com/umijs/umi-request",children:"umi-request"})," \u548C ",(0,s.jsx)(e.a,{href:"http://ahooks.js.org/hooks",children:"ahooks"})," \u7684 ",(0,s.jsx)(e.code,{children:"useRequest"})," \u63D0\u4F9B\u4E86\u4E00\u5957\u7EDF\u4E00\u7684\u7F51\u7EDC\u8BF7\u6C42\u548C\u9519\u8BEF\u5904\u7406\u65B9\u6848\u3002"]}),`
`,(0,s.jsxs)(e.h2,{id:"\u542F\u7528\u65B9\u5F0F",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u542F\u7528\u65B9\u5F0F",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u542F\u7528\u65B9\u5F0F"]}),`
`,(0,s.jsx)(e.p,{children:"\u9ED8\u8BA4\u542F\u7528\u3002"}),`
`,(0,s.jsxs)(e.h2,{id:"\u4ECB\u7ECD",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u4ECB\u7ECD",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u4ECB\u7ECD"]}),`
`,(0,s.jsx)(e.p,{children:"\u9519\u8BEF\u5904\u7406\u662F\u6240\u6709\u9879\u76EE\u90FD\u4F1A\u9047\u5230\u7684\u95EE\u9898\uFF0C\u6211\u4EEC\u7EA6\u5B9A\u4E86\u4E00\u4E2A\u63A5\u53E3\u683C\u5F0F\u89C4\u8303\u5982\u4E0B\uFF1A"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"typescript","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"typescript","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"interface"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"ErrorInfoStructure"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"success"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"boolean"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"; "}),(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// if request is success"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"data"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"any"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"; "}),(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// response data"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"errorCode"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"; "}),(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// code for errorType"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"errorMessage"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"; "}),(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// message display to user "})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(e.p,{children:["\u540E\u7AEF\u63A5\u53E3\u89C4\u8303\u4E0D\u6EE1\u8DB3\u7684\u60C5\u51B5\u4E0B\u4F60\u53EF\u4EE5\u901A\u8FC7\u914D\u7F6E ",(0,s.jsx)(e.code,{children:"errorConfig.adaptor"})," \u6765\u505A\u9002\u914D\u3002\u5F53 ",(0,s.jsx)(e.code,{children:"success"})," \u8FD4\u56DE\u662F ",(0,s.jsx)(e.code,{children:"false"})," \u7684\u60C5\u51B5\u6211\u4EEC\u4F1A\u6309\u7167 ",(0,s.jsx)(e.code,{children:"showType"})," \u548C ",(0,s.jsx)(e.code,{children:"errorMessage"})," \u6765\u505A\u7EDF\u4E00\u7684\u9519\u8BEF\u63D0\u793A\uFF0C\u540C\u65F6\u629B\u51FA\u4E00\u4E2A\u5F02\u5E38\u3002"]}),`
`,(0,s.jsx)(e.p,{children:"\u629B\u51FA\u7684\u5F02\u5E38\u7684\u683C\u5F0F\u4E3A\uFF1A"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"typescript","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"typescript","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"interface"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"RequestError"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"extends"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"Error"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"data"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"any"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"; "}),(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// \u8FD9\u91CC\u662F\u540E\u7AEF\u8FD4\u56DE\u7684\u539F\u59CB\u6570\u636E"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"info"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"ErrorInfoStructure"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(e.p,{children:["\u53E6\u5916\u4F60\u53EF\u4EE5\u901A\u8FC7 ",(0,s.jsx)(e.code,{children:"Error.name"})," \u662F\u5426\u662F ",(0,s.jsx)(e.code,{children:"BizError"})," \u6765\u5224\u65AD\u662F\u5426\u662F\u56E0\u4E3A ",(0,s.jsx)(e.code,{children:"success"})," \u4E3A ",(0,s.jsx)(e.code,{children:"false"})," \u629B\u51FA\u7684\u9519\u8BEF\u3002"]}),`
`,(0,s.jsxs)(e.h2,{id:"\u914D\u7F6E",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u914D\u7F6E",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u914D\u7F6E"]}),`
`,(0,s.jsxs)(e.h3,{id:"\u6784\u5EFA\u65F6\u914D\u7F6E",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u6784\u5EFA\u65F6\u914D\u7F6E",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u6784\u5EFA\u65F6\u914D\u7F6E"]}),`
`,(0,s.jsx)(e.p,{children:"\u5F53\u524D\u652F\u6301\u7684\u6784\u5EFA\u65F6\u914D\u7F6E\u5982\u4E0B\uFF1A"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"typescript","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"typescript","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"request:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"dataField:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'data'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  },"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`,(0,s.jsxs)(e.h4,{id:"datafield",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#datafield",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"dataField"]}),`
`,(0,s.jsxs)(e.ul,{children:[`
`,(0,s.jsxs)(e.li,{children:["Type: ",(0,s.jsx)(e.code,{children:"string"})]}),`
`]}),`
`,(0,s.jsxs)(e.p,{children:[(0,s.jsx)(e.code,{children:"dataField"})," \u5BF9\u5E94\u63A5\u53E3\u7EDF\u4E00\u683C\u5F0F\u4E2D\u7684\u6570\u636E\u5B57\u6BB5\uFF0C\u6BD4\u5982\u63A5\u53E3\u5982\u679C\u7EDF\u4E00\u7684\u89C4\u8303\u662F ",(0,s.jsx)(e.code,{children:"{ success: boolean, data: any}"})," \uFF0C\u90A3\u4E48\u5C31\u4E0D\u9700\u8981\u914D\u7F6E\uFF0C\u8FD9\u6837\u4F60\u901A\u8FC7 ",(0,s.jsx)(e.code,{children:"useRequest"})," \u6D88\u8D39\u7684\u65F6\u5019\u4F1A\u751F\u6210\u4E00\u4E2A\u9ED8\u8BA4\u7684 ",(0,s.jsx)(e.code,{children:"formatResult"}),"\uFF0C\u76F4\u63A5\u8FD4\u56DE ",(0,s.jsx)(e.code,{children:"data"})," \u4E2D\u7684\u6570\u636E\uFF0C\u65B9\u4FBF\u4F7F\u7528\u3002\u5982\u679C\u4F60\u7684\u540E\u7AEF\u63A5\u53E3\u4E0D\u7B26\u5408\u8FD9\u4E2A\u89C4\u8303\uFF0C\u53EF\u4EE5\u81EA\u884C\u914D\u7F6E ",(0,s.jsx)(e.code,{children:"dataField"})," \u3002\u914D\u7F6E\u4E3A ",(0,s.jsx)(e.code,{children:"''"})," \uFF08\u7A7A\u5B57\u7B26\u4E32\uFF09\u7684\u65F6\u5019\u4E0D\u505A\u5904\u7406\u3002"]}),`
`,(0,s.jsxs)(e.h3,{id:"\u8FD0\u884C\u65F6\u914D\u7F6E",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u8FD0\u884C\u65F6\u914D\u7F6E",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u8FD0\u884C\u65F6\u914D\u7F6E"]}),`
`,(0,s.jsxs)(e.p,{children:["\u5728 ",(0,s.jsx)(e.code,{children:"src/app.ts"})," \u4E2D\u4F60\u53EF\u4EE5\u914D\u7F6E\u4E00\u4E9B\u8FD0\u884C\u65F6\u7684\u914D\u7F6E\u9879\u6765\u5B9E\u73B0\u90E8\u5206\u81EA\u5B9A\u4E49\u9700\u6C42\u3002\u793A\u4F8B\u914D\u7F6E\u5982\u4E0B\uFF1A"]}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"typescript","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"typescript","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"RequestConfig"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#4FC1FF"},children:"request"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"RequestConfig"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"timeout:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#B5CEA8"},children:"1000"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"middlewares:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" [],"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"prefix:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'/api'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"method:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'get'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"errorHandler"}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"error"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// \u96C6\u4E2D\u5904\u7406\u9519\u8BEF"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"console"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"log"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#B5CEA8"},children:"11111111"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"console"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"log"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"error"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  },"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"requestInterceptors:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" [],"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"responseInterceptors:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" [],"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`,(0,s.jsxs)(e.p,{children:["\u8BE5\u914D\u7F6E\u8FD4\u56DE\u4E00\u4E2A\u5BF9\u8C61\u3002\u9664\u4E86",(0,s.jsx)(e.code,{children:"middlewares"})," \u4EE5\u5916\u5176\u5B83\u914D\u7F6E\u90FD\u662F\u76F4\u63A5\u900F\u4F20 ",(0,s.jsx)(e.a,{href:"https://github.com/umijs/umi-request",children:"umi-request"})," \u7684\u5168\u5C40\u914D\u7F6E\u3002"]}),`
`,(0,s.jsxs)(e.h4,{id:"middlewares",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#middlewares",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"middlewares"]}),`
`,(0,s.jsxs)(e.p,{children:["umi-request \u63D0\u4F9B",(0,s.jsx)(e.a,{href:"https://github.com/umijs/umi-request#middleware",children:"\u4E2D\u95F4\u4EF6\u673A\u5236"}),"\uFF0C\u4E4B\u524D\u662F\u901A\u8FC7 ",(0,s.jsx)(e.code,{children:"request.use(middleware)"})," \u7684\u65B9\u5F0F\u5F15\u5165\uFF0C\u73B0\u5728\u53EF\u4EE5\u901A\u8FC7 ",(0,s.jsx)(e.code,{children:"request.middlewares"})," \u8FDB\u884C\u914D\u7F6E\u3002"]}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"typescript","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"typescript","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#4FC1FF"},children:"request"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"middlewares:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"async"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"middlewareA"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"ctx"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"next"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"console"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"log"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'A before'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"await"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"next"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"console"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"log"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'A after'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    },"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"async"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"middlewareB"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"ctx"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"next"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"console"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"log"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'B before'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"await"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"next"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"console"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"log"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'B after'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    }"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  ]"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(e.h4,{id:"requestinterceptors",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#requestinterceptors",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"requestInterceptors"]}),`
`,(0,s.jsxs)(e.p,{children:["\u8BE5\u914D\u7F6E\u63A5\u6536\u4E00\u4E2A\u6570\u7EC4\uFF0C\u6570\u7EC4\u7684\u6BCF\u4E00\u9879\u4E3A\u4E00\u4E2A request \u62E6\u622A\u5668\u3002\u7B49\u540C\u4E8E umi-request \u7684 ",(0,s.jsx)(e.code,{children:"request.interceptors.request.use()"}),"\u3002\u5177\u4F53\u89C1 umi-request \u7684",(0,s.jsx)(e.a,{href:"https://github.com/umijs/umi-request#interceptor",children:"\u62E6\u622A\u5668\u6587\u6863"}),"\u3002"]}),`
`,(0,s.jsxs)(e.h4,{id:"responseinterceptors",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#responseinterceptors",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"responseInterceptors"]}),`
`,(0,s.jsxs)(e.p,{children:["\u8BE5\u914D\u7F6E\u63A5\u6536\u4E00\u4E2A\u6570\u7EC4\uFF0C\u6570\u7EC4\u7684\u6BCF\u4E00\u9879\u4E3A\u4E00\u4E2A response \u62E6\u622A\u5668\u3002\u7B49\u540C\u4E8E umi-request \u7684 ",(0,s.jsx)(e.code,{children:"request.interceptors.response.use()"}),"\u3002\u5177\u4F53\u89C1 umi-request \u7684",(0,s.jsx)(e.a,{href:"https://github.com/umijs/umi-request#interceptor",children:"\u62E6\u622A\u5668\u6587\u6863"}),"\u3002"]}),`
`,(0,s.jsxs)(e.h2,{id:"api",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#api",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"API"]}),`
`,(0,s.jsxs)(e.h3,{id:"userequest",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#userequest",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"useRequest"]}),`
`,(0,s.jsxs)(e.p,{children:["\u8BE5\u63D2\u4EF6\u5185\u7F6E\u4E86 ",(0,s.jsx)(e.a,{href:"https://ahooks.js.org/zh-CN/hooks/async",children:"@ahooksjs/use-request"}),"\uFF0C\u4F60\u53EF\u4EE5\u5728\u7EC4\u4EF6\u5185\u901A\u8FC7\u8BE5 Hook \u7B80\u5355\u4FBF\u6377\u7684\u6D88\u8D39\u6570\u636E\u3002\u793A\u4F8B\u5982\u4E0B\uFF1A"]}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"typescript","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"typescript","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"useRequest"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" () "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(e.span,{style:{color:"#4FC1FF"},children:"data"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#4FC1FF"},children:"error"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#4FC1FF"},children:"loading"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" } = "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"useRequest"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"(() "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"services"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"getUserList"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'/api/test'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  });"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"if"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"loading"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" <"}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"div"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:">"}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"loading"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"...</"}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"div"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:">;"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  }"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"if"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"error"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" <"}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"div"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:">{error."}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"message"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}</"}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"div"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:">;"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  }"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" <"}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"div"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:">{data."}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"name"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}</"}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"div"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:">;"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`,(0,s.jsxs)(e.p,{children:["\u66F4\u591A\u914D\u7F6E\u4F60\u53EF\u4EE5\u53C2\u8003  ",(0,s.jsx)(e.a,{href:"https://ahooks.js.org/zh-CN/hooks/async",children:"@ahooksjs/use-request"})," \u7684\u6587\u6863\u3002"]}),`
`,(0,s.jsxs)(e.p,{children:["\u4F60\u4E5F\u53EF\u4EE5\u67E5\u770B\u77E5\u4E4E\u4E13\u680F\u6587\u7AE0",(0,s.jsx)(e.a,{href:"https://zhuanlan.zhihu.com/p/106796295",children:"\u300AuseRequest- \u8682\u8681\u4E2D\u53F0\u6807\u51C6\u8BF7\u6C42 Hooks\u300B"}),"\u4E86\u89E3 useRequest\u3002"]}),`
`,(0,s.jsxs)(e.h3,{id:"request",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#request",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"request"]}),`
`,(0,s.jsxs)(e.p,{children:["\u901A\u8FC7 ",(0,s.jsx)(e.code,{children:"import { request } from 'alita';"})," \u4F60\u53EF\u4EE5\u4F7F\u7528\u5185\u7F6E\u7684\u8BF7\u6C42\u65B9\u6CD5\u3002 ",(0,s.jsx)(e.code,{children:"request"})," \u63A5\u6536\u4E24\u4E2A\u53C2\u6570\uFF0C\u7B2C\u4E00\u4E2A\u53C2\u6570\u662F ",(0,s.jsx)(e.code,{children:"url"}),"\uFF0C\u7B2C\u4E8C\u4E2A\u53C2\u6570\u662F\u8BF7\u6C42\u7684 ",(0,s.jsx)(e.code,{children:"options"}),"\u3002",(0,s.jsx)(e.code,{children:"options"})," \u5177\u4F53\u683C\u5F0F\u53C2\u8003 ",(0,s.jsx)(e.a,{href:"https://github.com/umijs/umi-request",children:"umi-request"}),"\u3002"]}),`
`,(0,s.jsxs)(e.p,{children:[(0,s.jsx)(e.code,{children:"request"})," \u7684\u5927\u90E8\u5206\u7528\u6CD5\u7B49\u540C\u4E8E ",(0,s.jsx)(e.code,{children:"umi-request"}),"\u3002"]}),`
`,(0,s.jsxs)(e.h3,{id:"requestconfig",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#requestconfig",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"RequestConfig"]}),`
`,(0,s.jsx)(e.p,{children:"\u8FD9\u662F\u4E00\u4E2A TypeScript \u5B9A\u4E49\uFF0C\u5B83\u53EF\u4EE5\u5E2E\u52A9\u4F60\u66F4\u597D\u7684\u914D\u7F6E\u8FD0\u884C\u65F6\u914D\u7F6E\u3002"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"typescript","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"typescript","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"RequestConfig"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#4FC1FF"},children:"request"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"RequestConfig"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" = {};"})]})]})})})]})}}c.default=D}}]);
