"use strict";(self.webpackChunkalita3=self.webpackChunkalita3||[]).push([[325],{1760:function(j,c,e){e.r(c);var i=e(57213),o=e.n(i),d=e(93236),s=e(62086);function h(){var n=arguments.length>0&&arguments[0]!==void 0?arguments[0]:{};(0,d.useEffect)(function(){var l;if(window.location.hash.length!==0){var D=decodeURIComponent(window.location.hash);setTimeout(function(){var r;(r=document.getElementById(D.slice(1)))===null||r===void 0||r.scrollIntoView()},100)}else window.scrollTo(0,0);(l=document.getElementById("active-nav-item"))===null||l===void 0||l.scrollIntoView({behavior:"smooth",block:"center"})},[]);var p=n.components||{},a=p.wrapper;return a?(0,s.jsx)(a,o()(o()({},n),{},{children:(0,s.jsx)(t,{})})):t();function t(){var l=Object.assign({h1:"h1",a:"a",span:"span",p:"p",h2:"h2",div:"div",pre:"pre",code:"code"},n.components);return(0,s.jsxs)(s.Fragment,{children:[(0,s.jsxs)(l.h1,{id:"helmet",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#helmet",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"Helmet"]}),`
`,(0,s.jsx)(l.p,{children:"\u7BA1\u7406 HTML \u6587\u6863\u6807\u7B7E\uFF08\u5982\u6807\u9898\u3001\u63CF\u8FF0\u7B49\uFF09"}),`
`,(0,s.jsxs)(l.h2,{id:"\u7528\u6CD5",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u7528\u6CD5",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u7528\u6CD5"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"tsx","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"tsx","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Helmet"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'react'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"App"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = () "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<>"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Helmet"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"title"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"Hello World"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"title"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"link"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"rel"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"canonical"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"href"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"https://www.tacobell.com/"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"/>"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Helmet"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"h1"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"Hello World"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"h1"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</>"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"App"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]})]})})})]})}}c.default=h}}]);
