"use strict";(self.webpackChunkalita3=self.webpackChunkalita3||[]).push([[336],{79896:function(x,r,e){e.r(r);var i=e(57213),o=e.n(i),t=e(93236),s=e(62086);function d(){var n=arguments.length>0&&arguments[0]!==void 0?arguments[0]:{};(0,t.useEffect)(function(){var l;if(window.location.hash.length!==0){var p=decodeURIComponent(window.location.hash);setTimeout(function(){var c;(c=document.getElementById(p.slice(1)))===null||c===void 0||c.scrollIntoView()},100)}else window.scrollTo(0,0);(l=document.getElementById("active-nav-item"))===null||l===void 0||l.scrollIntoView({behavior:"smooth",block:"center"})},[]);var h=n.components||{},a=h.wrapper;return a?(0,s.jsx)(a,o()(o()({},n),{},{children:(0,s.jsx)(D,{})})):D();function D(){var l=Object.assign({h1:"h1",a:"a",span:"span",p:"p",code:"code",div:"div",pre:"pre",h2:"h2"},n.components);return(0,s.jsxs)(s.Fragment,{children:[(0,s.jsxs)(l.h1,{id:"\u79FB\u52A8\u7AEF\u5E03\u5C40api",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u79FB\u52A8\u7AEF\u5E03\u5C40api",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u79FB\u52A8\u7AEF\u5E03\u5C40API"]}),`
`,(0,s.jsxs)(l.p,{children:["src/config/config.ts\u4E2D\u5F00\u542F ",(0,s.jsx)(l.code,{children:"mobileLayout"})," \u624D\u53EF\u4EE5\u4F7F\u7528\u79FB\u52A8\u7AEF\u5E03\u5C40API\u3002"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"defineConfig"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"defineConfig"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"mobileLayout:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"true"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"});"})})]})})}),`
`,(0,s.jsxs)(l.h2,{id:"setpagenavbar",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#setpagenavbar",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"setPageNavBar"]}),`
`,(0,s.jsxs)(l.p,{children:["\u8BE5\u65B9\u6CD5\u7528\u6765\u5B9A\u4E49\u67D0\u4E2A\u8DEF\u7531\u9875\u9762\u5934\u90E8\u5BFC\u822A\u4FE1\u606F\uFF0C\u5176\u63A5\u53D7\u4E00\u4E2A\u53C2\u6570 ",(0,s.jsx)(l.code,{children:"value: NavBarListItem"}),"\uFF0C\u53C2\u6570\u5B9A\u4E49\u5982\u4E0B\uFF1A"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"interface"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"NavBarListItem"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pagePath"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u9875\u9762\u8DEF\u5F84\uFF0C\u5FC5\u987B\u5728 pages \u4E2D\u5148\u5B9A\u4E49"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"navBar"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"NavBarProps"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5934\u90E8\u5BFC\u822A\u4FE1\u606F"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"interface"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"NavBarProps"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"{"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"mode"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'dark'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" | "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'light'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u98CE\u683C\u6A21\u5F0F"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"className"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u7C7B\u540D"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"back"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5934\u90E8\u5BFC\u822A\u5DE6\u4FA7\uFF0C\u8FD4\u56DE\u533A\u57DF\u7684\u6587\u5B57"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"icon"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"ReactNode"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5934\u90E8\u5BFC\u822A\u5DE6\u4FA7\uFF0C\u8FD4\u56DE\u533A\u57DF\u7684\u56FE\u6807"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"leftContent"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"ReactNode"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5934\u90E8\u5BFC\u822A\u5DE6\u4FA7\u7684\u8FD4\u56DE\u533A\u57DF\u7684\u53F3\u4FA7\u5185\u5BB9"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"rightContent"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"ReactNode"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5934\u90E8\u5BFC\u822A\u53F3\u4FA7\u5185\u5BB9"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"onLeftClick"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"navigate"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"void"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5934\u90E8\u5BFC\u822A\u5DE6\u8FB9\u8FD4\u56DE\u533A\u57DF\u70B9\u51FB\u56DE\u8C03"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"hideNavBar"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"boolean"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u662F\u5426\u663E\u793A\u5934\u90E8\u5BFC\u822A"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pageTitle"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5934\u90E8\u5BFC\u822A\u6807\u9898"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pageBackground"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u9875\u9762\u80CC\u666F\u989C\u8272"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsx)(l.p,{children:"\u793A\u4F8B\uFF1A"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"useEffect"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'react'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"useLocation"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"setPageNavBar"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"} "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"type"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"FC"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"} "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'react'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"Foo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"FC"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"props"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"location"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useLocation"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useEffect"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"(() "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"setPageNavBar"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pagePath:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"location"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pathname"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"navBar:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"mode:"}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'dark'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"className:"}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'test'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pageTitle:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u9875\u9762\u6807\u9898'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pageBackground:"}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'#fff'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"back:"}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u8FD4\u56DE'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"icon:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"LeftOutline"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" />,"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"leftContent:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"\u9996\u9875"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">,"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"rightContent:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"\u8BE6\u60C5"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">,"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"onLeftClick"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"navigate"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"          "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"navigate"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"(-"}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        },"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"hideNavBar:"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"false"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      },"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    });"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }, []);"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Foo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  )"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Foo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]})]})})}),`
`,(0,s.jsxs)(l.h2,{id:"getpagenavbar",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#getpagenavbar",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"getPageNavBar"]}),`
`,(0,s.jsxs)(l.p,{children:["\u83B7\u53D6\u901A\u8FC7",(0,s.jsx)(l.code,{children:"setPageNavBar"}),"\u5B9A\u4E49\u7684\u8DEF\u7531\u9875\u9762\u5934\u90E8\u5BFC\u822A\u4FE1\u606F\uFF0C\u8FD4\u56DE\u4E00\u4E2A\u5BF9\u8C61\uFF0C\u952E\u503C\u4E3A\u8DEF\u7531\u5730\u5740\uFF0C\u793A\u4F8B\uFF1A"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"useEffect"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'react'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"type"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"FC"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"} "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'react"}),(0,s.jsx)(l.span,{style:{color:"#F44747"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"getPageNavBar"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"Foo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"FC"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = () "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useEffect"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"(() "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"pageNavBar"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"getPageNavBar"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"console"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"log"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pageNavBar"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }, []);"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Foo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]})]})})}),`
`,(0,s.jsxs)(l.h2,{id:"settabbarlist",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#settabbarlist",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"setTabBarList"]}),`
`,(0,s.jsxs)(l.p,{children:["\u8BE5\u65B9\u6CD5\u7528\u6765\u8BBE\u7F6E\u9875\u9762\u5E95\u90E8\u5BFC\u822A\u6807\u7B7E\u3002\u5176\u63A5\u53D7\u4E00\u4E2A\u53C2\u6570 ",(0,s.jsx)(l.code,{children:"value: TabBarListItem | TabBarListItem[]"}),"\uFF0C\u53C2\u6570\u5B9A\u4E49\u5982\u4E0B\uFF1A"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"interface"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"TabBarListItem"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pagePath"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u9875\u9762\u8DEF\u5F84\uFF0C\u5FC5\u987B\u5728 pages \u4E2D\u5148\u5B9A\u4E49"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"text"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5BFC\u822A\u6807\u7B7E\u6587\u5B57"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"iconSize"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5BFC\u822A\u6807\u7B7E\u56FE\u6807\u5927\u5C0F"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"badge"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5BFC\u822A\u6807\u7B7E\u56FE\u6807\u5FAE\u6807\uFF08\u4E0A\u6807\uFF09"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"iconPath"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5BFC\u822A\u6807\u7B7E\u56FE\u6807\u8DEF\u5F84"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"selectedIconPath"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u9009\u4E2D\u65F6\u7684\u5BFC\u822A\u6807\u7B7E\u56FE\u6807\u8DEF\u5F84"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"onPress"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: () "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"void"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5BFC\u822A\u6807\u7B7E\u70B9\u51FB\u56DE\u8C03"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"title"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u9875\u9762\u6807\u9898"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"remove"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"boolean"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5220\u9664\u5BF9\u5E94\u7684\u5BFC\u822A\u6807\u7B7E"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"replace"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5C06\u539F\u5148\u5DF2\u6709\u5BFC\u822A\u6807\u7B7E\u7684\u5730\u5740\u66FF\u6362"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsx)(l.p,{children:"\u793A\u4F8B\uFF1A"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"useEffect"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'react'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"useLocation"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"setTabBarList"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"} "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"type"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"FC"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"} "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'react'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"Foo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"FC"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"props"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"location"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useLocation"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useEffect"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"(() "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"setTabBarList"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pagePath:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"location"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pathname"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"text:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u5F85\u529E'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"iconSize:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'18px'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"badge:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'12'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"iconPath:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'https://img1.baidu.com/it/u=1925990514,1559798685&fm=253&fmt=auto&app=138&f=JPEG?w=200&h=200'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"selectedIconPath:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'https://img1.baidu.com/it/u=2153806047,300205282&fm=253&fmt=auto&app=138&f=JPEG?w=200&h=200'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"onPress"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" () "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"navigate"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"location"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pathname"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", {"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"replace:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"true"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"});"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"''"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      },"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"title:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'\u5F85\u529E\u9875\u9762'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"remove:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"false"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// replace:'/list'"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    })"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }, []);"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Foo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  )"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Foo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]})]})})}),`
`,(0,s.jsxs)(l.h2,{id:"gettabbarlist",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#gettabbarlist",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"getTabBarList"]}),`
`,(0,s.jsxs)(l.p,{children:["\u83B7\u53D6\u901A\u8FC7",(0,s.jsx)(l.code,{children:"getTabBarList"}),"\u5B9A\u4E49\u7684\u8DEF\u7531\u9875\u9762\u5934\u90E8\u5BFC\u822A\u4FE1\u606F\uFF0C\u8FD4\u56DE\u4E00\u4E2A\u5BF9\u8C61\uFF0C\u952E\u503C\u4E3A\u8DEF\u7531\u5730\u5740\uFF0C\u793A\u4F8B\uFF1A"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"useEffect"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'react'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"type"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"FC"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"} "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'react"}),(0,s.jsx)(l.span,{style:{color:"#F44747"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"getTabBarList"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"Foo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"FC"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = () "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useEffect"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"(() "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"tabBarList"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"getTabBarList"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"console"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"log"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"tabBarList"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }, []);"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Foo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]})]})})})]})}}r.default=d}}]);
