"use strict";(self.webpackChunkalita3=self.webpackChunkalita3||[]).push([[925],{16645:function(x,r,e){e.r(r);var i=e(57213),o=e.n(i),d=e(93236),s=e(62086);function t(){var n=arguments.length>0&&arguments[0]!==void 0?arguments[0]:{};(0,d.useEffect)(function(){var l;if(window.location.hash.length!==0){var p=decodeURIComponent(window.location.hash);setTimeout(function(){var c;(c=document.getElementById(p.slice(1)))===null||c===void 0||c.scrollIntoView()},100)}else window.scrollTo(0,0);(l=document.getElementById("active-nav-item"))===null||l===void 0||l.scrollIntoView({behavior:"smooth",block:"center"})},[]);var h=n.components||{},a=h.wrapper;return a?(0,s.jsx)(a,o()(o()({},n),{},{children:(0,s.jsx)(D,{})})):D();function D(){var l=Object.assign({h1:"h1",a:"a",span:"span",h2:"h2",h3:"h3",p:"p",code:"code",div:"div",pre:"pre"},n.components);return(0,s.jsxs)(s.Fragment,{children:[(0,s.jsxs)(l.h1,{id:"\u5185\u7F6E\u7EC4\u4EF6",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u5185\u7F6E\u7EC4\u4EF6",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u5185\u7F6E\u7EC4\u4EF6"]}),`
`,(0,s.jsxs)(l.h2,{id:"\u8DEF\u7531\u76F8\u5173",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u8DEF\u7531\u76F8\u5173",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u8DEF\u7531\u76F8\u5173"]}),`
`,(0,s.jsxs)(l.h3,{id:"outlet",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#outlet",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"Outlet"]}),`
`,(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"<Outlet>"})," \u7528\u4E8E\u5728\u7236\u8DEF\u7531\u4E2D\u6E32\u67D3\u5B50\u8DEF\u7531\u3002\u5982\u679C\u7236\u8DEF\u7531\u88AB\u4E25\u683C\u5339\u914D\uFF0C\u4F1A\u6E32\u67D3\u5B50\u8DEF\u7531\u4E2D\u7684 index \u8DEF\u7531\uFF08\u5982\u6709\uFF09\u3002"]}),`
`,(0,s.jsx)(l.p,{children:"\u7C7B\u578B\u5B9A\u4E49\u5982\u4E0B\uFF1A"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"interface"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"OutletProps"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"context"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"unknown"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"declare"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"Outlet"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"props"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"OutletProps"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"): "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"ReactElement"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" | "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"null"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]})]})})}),`
`,(0,s.jsx)(l.p,{children:"\u793A\u4F8B\uFF1A"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Outlet"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"Dashboard"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"() {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"h1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Dashboard"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"h1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      <"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Outlet"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" />"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    </"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  );"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"DashboardWithContext"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"() {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"h1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Dashboard"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"h1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      <"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Outlet"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"context"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"={{ "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"prop:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'a'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" }}/>"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    </"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  );"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"Outlet"})," \u7EC4\u4EF6\u7684 ",(0,s.jsx)(l.code,{children:"context"})," \u53EF\u4EE5\u4F7F\u7528 API ",(0,s.jsx)(l.code,{children:"useOutletContext"})," \u5728\u5B50\u7EC4\u4EF6\u4E2D\u83B7\u53D6\u3002"]}),`
`,(0,s.jsxs)(l.h3,{id:"link",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#link",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"Link"]}),`
`,(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"<Link>"})," \u662F React \u7EC4\u4EF6\uFF0C\u662F\u5E26\u8DEF\u7531\u8DF3\u8F6C\u529F\u80FD\u7684 ",(0,s.jsx)(l.code,{children:"<a>"})," \u5143\u7D20\u3002"]}),`
`,(0,s.jsx)(l.p,{children:"\u7C7B\u578B\uFF1A"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"declare"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"Link"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"props"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"prefetch"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"boolean"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"to"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" | "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Partial"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"<{ "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"pathname"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"; "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"search"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"; "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"hash"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" }>;"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"replace"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"boolean"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"boolean"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"reloadDocument"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"boolean"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}): "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"ReactElement"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]})]})})}),`
`,(0,s.jsx)(l.p,{children:"\u793A\u4F8B\uFF1A"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Link"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"IndexPage"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"user"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" }) {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Link"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"to"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"={"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"user"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"id"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}>{user."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"name"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}</"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Link"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">;"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"<Link to>"})," \u652F\u6301\u76F8\u5BF9\u8DEF\u5F84\u8DF3\u8F6C\uFF1B",(0,s.jsx)(l.code,{children:"<Link reloadDocument>"})," \u4E0D\u505A\u8DEF\u7531\u8DF3\u8F6C\uFF0C\u7B49\u540C\u4E8E ",(0,s.jsx)(l.code,{children:"<a href>"})," \u7684\u8DF3\u8F6C\u884C\u4E3A\u3002"]}),`
`,(0,s.jsxs)(l.p,{children:["\u82E5\u5F00\u542F\u4E86 ",(0,s.jsx)(l.code,{children:"prefetch"})," \u5219\u5F53\u7528\u6237\u5C06\u9F20\u6807\u653E\u5230\u8BE5\u7EC4\u4EF6\u4E0A\u65B9\u65F6\uFF0CAlita \u5C31\u4F1A\u81EA\u52A8\u5F00\u59CB\u8FDB\u884C\u8DF3\u8F6C\u8DEF\u7531\u7684\u7EC4\u4EF6 js \u6587\u4EF6\u548C\u6570\u636E\u9884\u52A0\u8F7D\u3002"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Link"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"IndexPage"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"user"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" }) {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Link"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"to"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"={"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"user"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"id"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"} "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"prefetch"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">{user."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"name"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}</"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Link"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">;"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"navlink",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#navlink",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"NavLink"]}),`
`,(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"<NavLink>"})," \u662F ",(0,s.jsx)(l.code,{children:"<Link>"})," \u7684\u7279\u6B8A\u5F62\u6001\uFF0C\u4ED6\u77E5\u9053\u5F53\u524D\u662F\u5426\u4E3A\u8DEF\u7531\u6FC0\u6D3B\u72B6\u6001\u3002\u901A\u5E38\u5728\u5BFC\u822A\u83DC\u5355\u3001\u9762\u5305\u5C51\u3001Tabs \u4E2D\u4F1A\u4F7F\u7528\uFF0C\u7528\u4E8E\u663E\u793A\u5F53\u524D\u7684\u9009\u4E2D\u72B6\u6001\u3002"]}),`
`,(0,s.jsx)(l.p,{children:"\u7C7B\u578B\uFF1A"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"declare"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"NavLink"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"props"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"LinkProps"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" & {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"caseSensitive"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"boolean"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"children"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"ReactNode"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" | (("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"props"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"isActive"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"boolean"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" }) "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"ReactNode"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"className"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" | (("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"props"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"isActive"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"boolean"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" }) "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" | "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"undefined"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"end"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"boolean"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"style"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"?: "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"CSSProperties"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" | (("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"props"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"isActive"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"boolean"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" }) "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" | "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"CSSProperties"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}): "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"ReactElement"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]})]})})}),`
`,(0,s.jsx)(l.p,{children:"\u4E0B\u65B9\u793A\u4F8B\u5206\u522B\u7528\u4E86 style\u3001className \u548C children \u6765\u6E32\u67D3 active \u72B6\u6001\u3002"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"NavLink"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"Navs"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"() {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"ul"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"li"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"><"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"NavLink"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"to"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"message"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"style"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"={({ "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"isActive"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" }) "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"isActive"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ? { "}),(0,s.jsx)(l.span,{style:{color:"#C8C8C8"},children:"color"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'red'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } : "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"undefined"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}>"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Messages"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"NavLink"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"></"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"li"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"li"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"><"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"NavLink"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"to"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"tasks"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"className"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"={({ "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"isActive"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" }) "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"isActive"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ? 'active' : undefined}>"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Tasks"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"NavLink"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"></"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"li"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"li"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"><"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"NavLink"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"to"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"blog"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">{({ "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"isActive"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" }) "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"span"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"className"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"={"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"isActive"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ? "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'active'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" : "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"undefined"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}>"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Blog"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"span"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">}</"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"NavLink"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"></"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"li"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  </"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"ul"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">;"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.h2,{id:"html\u6587\u6863\u76F8\u5173",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#html\u6587\u6863\u76F8\u5173",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"HTML\u6587\u6863\u76F8\u5173"]}),`
`,(0,s.jsxs)(l.h3,{id:"helmet",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#helmet",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"Helmet"]}),`
`,(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"Helmet"})," \u662F\u5185\u7F6E ",(0,s.jsx)(l.code,{children:"plugin-helmet"})," \u63D2\u4EF6\u63D0\u4F9B\u7684\u7EC4\u4EF6\uFF0C\u82E5\u7EC4\u4EF6\u5F15\u7528\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5 ",(0,s.jsx)(l.code,{children:"plugin-helmet"})," \u63D2\u4EF6\u662F\u5426\u5B89\u88C5\u6210\u529F\u3002"]}),`
`,(0,s.jsx)(l.p,{children:"\u7528\u6765\u7BA1\u7406 HTML \u6587\u6863\u6807\u7B7E\uFF08\u5982\u6807\u9898\u3001\u63CF\u8FF0\u7B49\uFF09\u3002"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Helmet"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'react'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"App"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = () "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  <>"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Helmet"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"title"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Hello"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"World"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"title"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      <"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"link"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"rel"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"canonical"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"href"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"https://www.tacobell.com/"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" />"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    </"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Helmet"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    <"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"h1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Hello"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"World"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"h1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  </>"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"App"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]})]})})}),`
`,(0,s.jsxs)(l.p,{children:["\u5C06\u4F1A\u5728 html \u9875\u9762\u7684 ",(0,s.jsx)(l.code,{children:"head"})," \u6807\u7B7E\u5185\u6DFB\u52A0\uFF1A"]}),`
`,(0,s.jsx)(l.pre,{children:(0,s.jsx)(l.code,{children:`<head>
  <title>Hello World</title>
  <link rel="canonical" href="https://www.tacobell.com/" data-rh="true">
</head>
`})})]})}}r.default=t}}]);
