"use strict";(self.webpackChunkalita3=self.webpackChunkalita3||[]).push([[235],{40185:function(x,r,l){l.r(r);var i=l(57213),o=l.n(i),d=l(93236),e=l(62086);function D(){var n=arguments.length>0&&arguments[0]!==void 0?arguments[0]:{};(0,d.useEffect)(function(){var s;if(window.location.hash.length!==0){var p=decodeURIComponent(window.location.hash);setTimeout(function(){var c;(c=document.getElementById(p.slice(1)))===null||c===void 0||c.scrollIntoView()},100)}else window.scrollTo(0,0);(s=document.getElementById("active-nav-item"))===null||s===void 0||s.scrollIntoView({behavior:"smooth",block:"center"})},[]);var h=n.components||{},a=h.wrapper;return a?(0,e.jsx)(a,o()(o()({},n),{},{children:(0,e.jsx)(t,{})})):t();function t(){var s=Object.assign({h2:"h2",a:"a",span:"span",h3:"h3",p:"p",code:"code",div:"div",pre:"pre"},n.components);return(0,e.jsxs)(e.Fragment,{children:[(0,e.jsxs)(s.h2,{id:"\u5176\u4ED6api",children:[(0,e.jsx)(s.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u5176\u4ED6api",children:(0,e.jsx)(s.span,{className:"icon icon-link"})}),"\u5176\u4ED6API"]}),`
`,(0,e.jsxs)(s.h3,{id:"usekeepoutlets",children:[(0,e.jsx)(s.a,{"aria-hidden":"true",tabIndex:"-1",href:"#usekeepoutlets",children:(0,e.jsx)(s.span,{className:"icon icon-link"})}),"useKeepOutlets"]}),`
`,(0,e.jsxs)(s.p,{children:["\u8BE5 API \u9700\u8981\u5728src/config/config.ts\u4E2D\u914D\u7F6E ",(0,e.jsx)(s.code,{children:"keepalive"})," \u624D\u53EF\u4EE5\u4F7F\u7528\u3002"]}),`
`,(0,e.jsx)(s.div,{"data-rehype-pretty-code-fragment":"",children:(0,e.jsx)(s.pre,{"data-language":"ts","data-theme":"default",children:(0,e.jsxs)(s.code,{"data-language":"ts","data-theme":"default",children:[(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"import"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" { "}),(0,e.jsx)(s.span,{style:{color:"#9CDCFE"},children:"defineConfig"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" } "}),(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"from"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,e.jsx)(s.span,{className:"line",children:" "}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"export"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"default"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#DCDCAA"},children:"defineConfig"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"  "}),(0,e.jsx)(s.span,{style:{color:"#9CDCFE"},children:"keepalive:"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" ["}),(0,e.jsx)(s.span,{style:{color:"#CE9178"},children:"'/list'"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"],"})]}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"});"})})]})})}),`
`,(0,e.jsxs)(s.p,{children:["\u5982\u679C\u4F60\u6CA1\u6709\u4F7F\u7528 ",(0,e.jsx)(s.code,{children:"mobileLayout"}),"\uFF0C\u800C\u662F\u81EA\u5B9A\u4E49\u7684 ",(0,e.jsx)(s.code,{children:"layout"})," \uFF0C\u5373\u9879\u76EE\u4E2D\u5B58\u5728 ",(0,e.jsx)(s.code,{children:"src/layouts/index.tsx"}),`\u3002
\u9700\u8981\u4F7F\u7528 `,(0,e.jsx)(s.code,{children:"useKeepOutlets"})," \u83B7\u53D6\u5230 ",(0,e.jsx)(s.code,{children:"OutLet"}),"\uFF0C\u624D\u80FD\u4F7F\u7528 ",(0,e.jsx)(s.code,{children:"keepalive"})," \u914D\u7F6E\u9700\u8981\u72B6\u6001\u4FDD\u6301\u7684\u8DEF\u7531\u3002"]}),`
`,(0,e.jsx)(s.div,{"data-rehype-pretty-code-fragment":"",children:(0,e.jsx)(s.pre,{"data-language":"ts","data-theme":"default",children:(0,e.jsxs)(s.code,{"data-language":"ts","data-theme":"default",children:[(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"import"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#9CDCFE"},children:"React"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"from"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#CE9178"},children:"'react'"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"import"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"type"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" {"}),(0,e.jsx)(s.span,{style:{color:"#9CDCFE"},children:"FC"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"} "}),(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"from"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#CE9178"},children:"'react'"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"import"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" { "}),(0,e.jsx)(s.span,{style:{color:"#9CDCFE"},children:"useKeepOutlets"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"} "}),(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"from"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#CE9178"},children:"'alita'"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,e.jsx)(s.span,{className:"line",children:" "}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#569CD6"},children:"const"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#DCDCAA"},children:"Layout"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:": "}),(0,e.jsx)(s.span,{style:{color:"#4EC9B0"},children:"FC"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" = () "}),(0,e.jsx)(s.span,{style:{color:"#569CD6"},children:"=>"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"  "}),(0,e.jsx)(s.span,{style:{color:"#569CD6"},children:"const"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#4FC1FF"},children:"OutLet"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" = "}),(0,e.jsx)(s.span,{style:{color:"#DCDCAA"},children:"useKeepOutlets"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"  "}),(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"return"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" <>{"}),(0,e.jsx)(s.span,{style:{color:"#9CDCFE"},children:"OutLet"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"}</>;"})]}),`
`,(0,e.jsx)(s.span,{className:"line",children:(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:"};"})}),`
`,(0,e.jsx)(s.span,{className:"line",children:" "}),`
`,(0,e.jsxs)(s.span,{className:"line",children:[(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"export"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#C586C0"},children:"default"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:" "}),(0,e.jsx)(s.span,{style:{color:"#9CDCFE"},children:"Layout"}),(0,e.jsx)(s.span,{style:{color:"#D4D4D4"},children:";"})]})]})})})]})}}r.default=D}}]);
