// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { request } from '/Users/congxiaochen/Documents/alita/packages/request';
export { useRequest } from '@fs/Users/congxiaochen/Documents/alita/node_modules/.pnpm/ahooks@3.1.5/node_modules/ahooks';
