import { join } from 'path';
import px2rem, { IOpts } from 'postcss-plugin-px2rem';
import { IApi } from 'umi';

export interface HdOptions {
  theme?: object;
  px2rem?: IOpts;
}
const antdHdTheme = {
  'font-size-base': '28px',
  'font-size-sm': '24px',
  'border-radius-base': '4px',
  'padding-lg': '48px',
  'padding-md': '32px',
  'padding-sm': '24px',
  'padding-xs': '16px',
  'padding-xss': '8px',
  'margin-lg': '48px',
  'margin-md': '32px',
  'margin-sm': '24px',
  'margin-xs': '16px',
  'margin-xss': '8px',
  'height-base': '64px',
  'height-lg': '80px',
  'height-sm': '48px',
  'border-width-base': '1px',
  'outline-width': '4px',
  'btn-shadow': '0 8px 0 rgba(0, 0, 0, 0.015)',
  'btn-primary-shadow': '0 4px 0 rgba(0, 0, 0, 0.045)',
  'btn-text-shadow': '0 -1px 0 rgba(0, 0, 0, 0.12)',
  'checkbox-size': '32px',
  'checkbox-group-item-margin-right': '16px',
  'descriptions-title-margin-bottom': '40px',
  'descriptions-item-label-colon-margin-right': '16px',
  'descriptions-item-label-colon-margin-left': '4px',
  'divider-text-padding': '1em',
  'radio-size': '32px',
  'radio-top': '0.2em',
  'radio-border-width': '1px',
  'radio-wrapper-margin-right': '16px',

  'layout-header-height': '128px',
  'layout-header-padding': '0 100px',
  'layout-footer-padding': '48px 100px',
  'layout-trigger-height': '96px',
  'layout-zero-trigger-width': '72px',
  'layout-zero-trigger-height': '84px',
  'dropdown-vertical-padding': '10px',
  'dropdown-edge-child-vertical-padding': '8px',
  'dropdown-line-height': '44px',
  'form-item-margin-bottom': '48px',
  'form-vertical-label-padding': '0 0 16px',
  'form-item-label-colon-margin-right': '16px',
  'form-item-label-colon-margin-left': '4px',
  'select-dropdown-height': '64px',
  'select-single-item-height-lg': '80px',
  'select-multiple-item-height-lg': '64px',
  'anchor-link-top': '14px',
  'anchor-link-left': '32px',
  'tooltip-max-width': '500px',
  'tooltip-arrow-width': '10px',
  'popover-min-width': '354px',
  'popover-min-height': '64px',
  'popover-arrow-width': '12px',
  'modal-header-title-line-height': '44px',
  'modal-header-close-size': '112px',
  'modal-footer-padding-vertical': '20px',
  'modal-footer-padding-horizontal': '32px',
  'modal-confirm-body-padding': '64px 64px 48px',
  'progress-radius': '200px',
  'menu-inline-toplevel-item-height': '80px',
  'menu-item-height': '80px',
  'menu-collapsed-width': '160px',
  'menu-item-active-border-width': '6px',
  'menu-item-vertical-margin': '8px',
  'menu-item-boundary-margin': '16px',
  'menu-item-padding-horizontal': '40px',
  'menu-horizontal-line-height': '92px',
  'menu-icon-margin-right': '20px',
  'spin-dot-size-sm': '28px',
  'spin-dot-size': '40px',
  'spin-dot-size-lg': '64px',
  'table-padding-vertical': '32px',
  'table-padding-horizontal': '32px',
  'table-selection-column-width': '64px',
  'table-sticky-scroll-bar-radius': '8px',
  'tag-line-height': '40px',
  'picker-time-panel-column-width': '112px',
  'picker-time-panel-column-height': '448px',
  'picker-time-panel-cell-height': '56px',
  'picker-panel-cell-height': '48px',
  'picker-panel-cell-width': '72px',
  'picker-text-height': '80px',
  'picker-panel-without-time-cell-height': '132px',
  'carousel-dot-width': '32px',
  'carousel-dot-height': '6px',
  'carousel-dot-active-width': '48px',
  'badge-height': '40px',
  'badge-height-sm': '28px',
  'badge-dot-size': '12px',
  'badge-status-size': '12px',
  'rate-star-size': '40px',
  'card-head-padding': '32px',
  'card-head-height': '96px',
  'card-head-height-sm': '72px',
  'card-inner-head-padding': '24px',
  'card-padding-base': '48px',
  'card-actions-li-margin': '24px 0',
  'card-head-tabs-margin-bottom': '-34px',
  'comment-nest-indent': '88px',
  'tabs-card-height': '80px',
  'tabs-horizontal-gutter': '64px',
  'tabs-horizontal-margin-rtl': '0 0 0 64px',
  'tabs-scrolling-size': '64px',
  'tabs-card-gutter': '4px',
  'tabs-card-tab-active-border-top': '4px solid transparent',
  'avatar-size-base': '64px',
  'avatar-size-lg': '80px',
  'avatar-size-sm': '48px',
  'avatar-font-size-base': '36px',
  'avatar-font-size-lg': '48px',
  'avatar-font-size-sm': '28px',
  'avatar-group-overlapping': '-16px',
  'avatar-group-space': '6px',
  'switch-height': '44px',
  'switch-sm-height': '32px',
  'switch-min-width': '88px',
  'switch-sm-min-width': '56px',
  'switch-padding': '4px',
  'pagination-item-size-sm': '48px',
  'page-header-heading-sub-title': '28px',
  'page-header-tabs-tab-font-size': '32px',
  'slider-margin': '20px 12px 20px',
  'slider-handle-border-width': '4px',
  'slider-handle-size': '28px',
  'slider-handle-margin-top': '-10px',
  'tree-title-height': '48px',
  'tree-child-padding': '36px',
  'collapse-header-padding-extra': '80px',
  'collapse-header-arrow-left': '32px',
  'skeleton-paragraph-margin-top': '56px',
  'skeleton-paragraph-li-height': '32px',
  'skeleton-title-height': '32px',
  'transfer-header-height': '80px',
  'transfer-list-height': '400px',
  'transfer-item-padding-vertical': '12px',
  'transfer-list-search-icon-top': '24px',
  'message-notice-content-padding': '20px 32px',
  'wave-animation-width': '12px',
  'alert-with-description-icon-size': '48px',
  'list-item-padding-lg': '32px 48px',
  'statistic-content-font-size': '48px',
  'statistic-unit-font-size': '48px',
  'drawer-header-close-size': '112px',
  'timeline-width': '4px',
  'timeline-dot-border-width': '4px',
  'timeline-item-padding-bottom': '40px',
  'steps-icon-size': '64px',
  'steps-icon-custom-top': '0px',
  'steps-icon-custom-font-size': '48px',
  'steps-icon-top': '-1px',
  'steps-icon-margin': '0 16px 0 0',
  'steps-small-icon-size': '48px',
  'steps-small-icon-margin': '0 16px 0 0',
  'steps-dot-size': '16px',
  'steps-dot-top': '4px',
  'steps-current-dot-size': '20px',
  'steps-description-max-width': '280px',
  'steps-vertical-icon-width': '32px',
  'steps-vertical-tail-width': '32px',
  'steps-vertical-tail-width-sm': '24px',
  'notification-padding-vertical': '32px',
  'notification-padding-horizontal': '48px',
  'result-title-font-size': '48px',
  'result-icon-font-size': '144px',
  'result-extra-margin': '48px 0 0 0',
  'image-size-base': '96px',
  'image-font-size-base': '48px',
  'image-mask-font-size': '32px',
  'image-preview-operation-size': '36px',
};
export default (api: IApi) => {
  const {
    utils: { getFile },
  } = api;

  api.describe({
    key: 'hd',
    config: {
      schema(joi) {
        return joi.object({
          theme: joi.object(),
          px2rem: joi.object(),
        });
      },
    },
  });

  if (api.userConfig.hd || api.userConfig.appType !== 'pc') {
    api.modifyDefaultConfig((config) => {
      const draftConfig = config;
      const { theme, px2rem: configPx2rem } = api.userConfig?.hd || {};
      draftConfig.theme = {
        ...antdHdTheme,
        ...(draftConfig.theme || {}),
        '@hd': '2px',
        ...(theme || {}),
      };
      draftConfig.extraPostCSSPlugins = [
        ...(draftConfig.extraPostCSSPlugins || []),
        px2rem({
          rootValue: 100,
          minPixelValue: 2,
          ...(configPx2rem || {}),
        }),
      ];
      return draftConfig;
    });

    api.addEntryImports(() => {
      // src/hd.(tsx|ts|jsx|js)
      const hdFile = getFile({
        base: api.paths.absSrcPath || '',
        type: 'javascript',
        fileNameWithoutExt: 'hd',
      });
      return {
        source: hdFile
          ? require.resolve(hdFile.path)
          : require.resolve(join(__dirname, 'template.js')),
      };
    });
  }
};
