// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import './core/polyfill';

import { renderClient } from '@fs/Users/congxiaochen/Desktop/poplar/node_modules/@umijs/renderer-react';
import { getRoutes } from './core/route';
import { createPluginManager } from './core/plugin';
import { createHistory } from './core/history';
import { ApplyPluginsType, PluginManager } from 'umi';
import VConsole from '@fs/Users/congxiaochen/Desktop/poplar/node_modules/@alita/plugins/compiled/vconsole';
import './plugin-hd/hd.tsx';

async function render() {
  const pluginManager = createPluginManager();
  const { routes, routeComponents } = await getRoutes(pluginManager);

  // allow user to extend routes
  pluginManager.applyPlugins({
    key: 'patchRoutes',
    type: 'event',
    args: {
      routes,
      routeComponents,
    },
  });
  const context = {
    routes,
    routeComponents,
    pluginManager,
    rootElement: document.getElementById('root'),
    history: createHistory({
      type: 'hash',
    }),
    basename: '/',
  };

  return (pluginManager.applyPlugins({
    key: 'render',
    type: ApplyPluginsType.compose,
    initialValue() {
      return renderClient(context);
    },
  }))();
}


import { getPluginManager } from './core/plugin';
  
  import { setRequestConfig } from '@fs/Users/congxiaochen/Desktop/poplar/node_modules/@alita/request';
render();
const c = new VConsole({});
setRequestConfig(getPluginManager().applyPlugins({ key: 'request',type: 'modify', initialValue: {} }))
