// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// @umijs/renderer-react
export { createBrowserHistory, createHashHistory, createMemoryHistory, createSearchParams, Link, matchPath, matchRoutes, NavLink, Outlet, useLocation, useMatch, useNavigate, useOutlet, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, renderClient, useRouteData } from '@fs/Users/congxiaochen/Documents/alita/node_modules/.pnpm/@umijs+renderer-react@4.0.0-rc.1_react-dom@17.0.2+react@17.0.2/node_modules/@umijs/renderer-react';
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '@fs/Users/congxiaochen/Documents/alita/node_modules/.pnpm/umi@4.0.0-rc.1/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
// plugins
export { connect, useDispatch, useStore, useSelector } from './plugin-dva';
export { KeepAliveContext, useKeepOutlets } from './plugin-keepalive';
export { getPageNavBar, setPageNavBar, setTabBarList, getTabBarList, layoutEmitter } from './plugin-mobile-layout';
export { Provider, useModel } from './plugin-model';
export { request, useRequest } from './plugin-request';
// plugins types.ts
export * from './plugin-dva/types.d';
