// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export async function getRoutes() {
  return {
    routes: {"property/index":{"path":"property","id":"property/index","parentId":"alita-layout","file":"property/index.tsx"},"message/index":{"path":"message","id":"message/index","parentId":"alita-layout","file":"message/index.tsx"},"life/index":{"path":"life","id":"life/index","parentId":"alita-layout","file":"life/index.tsx"},"my/index":{"path":"my","id":"my/index","parentId":"alita-layout","file":"my/index.tsx"},"index":{"path":"/","id":"index","parentId":"alita-layout","file":"index.tsx"},"alita-layout":{"id":"alita-layout","path":"/","file":"/Users/congxiaochen/Desktop/poplar/src/.umi/plugin-mobile-layout/AlitaLayout.tsx"}},
    routeComponents: {
'property/index': () => import('../../../src/pages/property/index.tsx'),
'message/index': () => import('../../../src/pages/message/index.tsx'),
'life/index': () => import('../../../src/pages/life/index.tsx'),
'my/index': () => import('../../../src/pages/my/index.tsx'),
'index': () => import('../../../src/pages/index.tsx'),
'alita-layout': () => import('../plugin-mobile-layout/AlitaLayout.tsx'),
},
  };
}
