// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/congxiaochen/Desktop/poplar/src/models/todo.ts';

export const models = {
model_1: { namespace: 'todo', model: model_1 },
}
